force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <displayFormat>BL-{000000000}</displayFormat>
        <label>Backlog No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Backlog__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Month</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Select date of the Month</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/classVerifyBacklogsMonth.cls
global class classVerifyBacklogsMonth implements Schedulable{
	global void execute(SchedulableContext SC) {
		List<Backlog__c> listBacklogUpdate = [SELECT Id, Current_Month__c
												FROM Backlog__c
												WHERE (Date__c = THIS_MONTH
												AND Current_Month__c = false)
												OR (Date__c != THIS_MONTH
												AND Current_Month__c = true)];
		
		for(Backlog__c backlog: listBacklogUpdate){
			backlog.Current_Month__c = !backlog.Current_Month__c;
		}
		
		update listBacklogUpdate;
	}
}