force-app/main/default/objects/Case/fields/PNG_CaseType__c.field-meta.xml
<CustomField>
    <fullName>PNG_CaseType__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>ICT &amp; GSM</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Case/fields/PNG_RootCause__c.field-meta.xml
<CustomField>
    <fullName>PNG_RootCause__c</fullName>
    <label>Root Cause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fibre Damage</fullName>
            </value>
            <value>
                <fullName>LAN issue</fullName>
            </value>
            <value>
                <fullName>Line of Sight</fullName>
            </value>
            <value>
                <fullName>03B Outage</fullName>
            </value>
            <value>
                <fullName>PMP Node Offline</fullName>
            </value>
            <value>
                <fullName>SM Idle</fullName>
            </value>
            <value>
                <fullName>Power Issue – site</fullName>
            </value>
            <value>
                <fullName>Power Issue – customer</fullName>
            </value>
            <value>
                <fullName>IP core issue</fullName>
            </value>
            <value>
                <fullName>International link issue</fullName>
            </value>
            <value>
                <fullName>Transmission issue</fullName>
            </value>
            <value>
                <fullName>RF Interference</fullName>
            </value>
            <value>
                <fullName>Capacity exceeded</fullName>
            </value>
            <value>
                <fullName>Faulty equipment – customer</fullName>
            </value>
            <value>
                <fullName>Faulty play box-no power</fullName>
            </value>
            <value>
                <fullName>Faulty connectors/splitters-loose/broken</fullName>
            </value>
            <value>
                <fullName>Faulty cable-cut/worn out</fullName>
            </value>
            <value>
                <fullName>Broken/Damaged Antenna or Dish</fullName>
            </value>
            <value>
                <fullName>Faulty parts &gt; example: LNB/Amplifier/etc…</fullName>
            </value>
            <value>
                <fullName>Relocation/Move</fullName>
            </value>
            <value>
                <fullName>Relocate of antenna/dish</fullName>
            </value>
            <value>
                <fullName>Removal of equipment(antenna/dish/cable)</fullName>
            </value>
            <value>
                <fullName>New Hook up(s)</fullName>
            </value>
            <value>
                <fullName>Additional Installation(s)</fullName>
            </value>
            <value>
                <fullName>Swap from DTT to DTH</fullName>
            </value>
            <value>
                <fullName>Extension of cable(s)</fullName>
            </value>
            <value>
                <fullName>Termination &amp; Commissioning</fullName>
            </value>
            <value>
                <fullName>No signal</fullName>
            </value>
            <value>
                <fullName>Scramble message</fullName>
            </value>
            <value>
                <fullName>Pixelate pictures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/PNG_SupportCase.recordType-meta.xml
<RecordType>
    <fullName>PNG_SupportCase</fullName>
    <active>true</active>
    <businessProcess>Digicel PNG ICT %26 GSM Support Process</businessProcess>
    <label>Digicel PNG Support Case</label>
</RecordType>

force-app/main/default/objects/Entitlement/fields/PNG_EntitlementType__c.field-meta.xml
<CustomField>
    <fullName>PNG_EntitlementType__c</fullName>
    <label>Entitlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Services</fullName>
            </value>
            <value>
                <fullName>Connectivity &amp; Enterprise Services</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PNG_CaseManagementTriggerTest.cls
@isTest
public class PNG_CaseManagementTriggerTest {
    static Id supportCaseRecId = [Select id from RecordType where sObjectType = 'Case' and developername ='PNG_SupportCase'].id ;
    
	@testSetup static void setup() {
                Case parentCase = new Case(Status='New', RecordTypeId= supportCaseRecId, Subject='Parent Case', PNG_RootCause__c = 'LAN issue');
        insert parentCase;
        
    }
     @isTest
    public static void testCloseNoChildCases(){
        Case parentCase = [SELECT Id, Status,PNG_RootCause__c FROM Case WHERE Subject=:'Parent Case' LIMIT 1];
        Test.startTest();
        parentCase.Status = 'Closed';
        update parentCase;
        Test.stopTest();
        System.assertEquals(parentCase.PNG_RootCause__c, 'LAN issue');
    }
    @isTest
    public static void testCloseAllLevelOChildCases(){
        Case parentCase = [SELECT Id, Status,PNG_RootCause__c FROM Case WHERE Subject=:'Parent Case' LIMIT 1];
        Case childCase = new Case(Status='New', RecordTypeId= supportCaseRecId, Subject='Child Case', ParentId = parentCase.Id,
                                  PNG_RootCause__c = 'Line of Sight');
        insert childCase;
        Test.startTest();
        parentCase.Status = 'Closed';
        update parentCase;
        Test.stopTest();
        Case closedChildCase = [SELECT Id, PNG_RootCause__c FROM Case WHERE ParentId =: parentCase.Id LIMIT 1];
        System.assertEquals(parentCase.PNG_RootCause__c, closedChildCase.PNG_RootCause__c);
    }
     @isTest
    	public static void testSelectEntitlementGSM(){
            Account acc = new Account(Name='Test Acc1', Type='Customer');
        	insert acc;
            Entitlement ent = new Entitlement(Name = 'Test Entitlement',AccountId = acc.id, PNG_EntitlementType__c ='Mobile Services',
                                             StartDate = System.Today()-1, EndDate = System.Today()+2);
           	insert ent;
            Case parentCase = [SELECT Id FROM Case WHERE Subject=:'Parent Case' LIMIT 1]; 
            Test.startTest();
            parentCase.AccountId = acc.Id;
            parentCase.PNG_CaseType__c = 'GSM';
            update parentCase;
            Test.stopTest();
           	Case updatedCase = [SELECT Id, EntitlementId FROM Case WHERE Subject=:'Parent Case' LIMIT 1];
            System.assertEquals(updatedCase.EntitlementId, ent.id);
        }
    @isTest
    	public static void testSelectEntitlementICT(){
            Account acc = new Account(Name='Test Acc1', Type='Customer');
        	insert acc;
            Entitlement ent = new Entitlement(Name = 'Test Entitlement',AccountId = acc.id, PNG_EntitlementType__c ='Connectivity & Enterprise Services',
                                             StartDate = System.Today()-1, EndDate = System.Today()+2);
           	insert ent;
            Case parentCase = [SELECT Id FROM Case WHERE Subject=:'Parent Case' LIMIT 1]; 
            Test.startTest();
            parentCase.AccountId = acc.Id;
            parentCase.PNG_CaseType__c = 'ICT';
            update parentCase;
            Test.stopTest();
           	Case updatedCase = [SELECT Id, EntitlementId FROM Case WHERE Subject=:'Parent Case' LIMIT 1];
            System.assertEquals(updatedCase.EntitlementId, ent.id);
        }
}