DigicielFull/force-app/main/default/objects/ICT_User_Target_Records__c/ICT_User_Target_Records__c.object-meta.xml
<CustomObject>
    <label>ICT User Target Records</label>
    <nameField>
        <displayFormat>User-{0000000}</displayFormat>
        <label>ICT User Target Records Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICT User Target Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICT_User_Target_Records__c/fields/ICT_Sales_Represenative__c.field-meta.xml
<CustomField>
    <fullName>ICT_Sales_Represenative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICT Sales Represenative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ICT_User_Target_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/Monthly_ICT_GSM_Targets__c.object-meta.xml
<CustomObject>
    <label>Monthly ICT &amp; GSM Targets</label>
    <nameField>
        <displayFormat>Digicel-{0000000}</displayFormat>
        <label>Monthly ICT &amp; GSM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly ICT &amp; GSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/ICT_Monthly_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>ICT_Monthly_Revenue_Target__c</fullName>
    <label>ICT Monthly Revenue Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/ICT_User_Target_Records__c.field-meta.xml
<CustomField>
    <fullName>ICT_User_Target_Records__c</fullName>
    <label>ICT User Target Records</label>
    <referenceTo>ICT_User_Target_Records__c</referenceTo>
    <relationshipLabel>Monthly ICT &amp; GSM Targets</relationshipLabel>
    <relationshipName>Monthly_ICT_GSM_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Monthly_OCT__c.field-meta.xml
<CustomField>
    <fullName>Monthly_OCT__c</fullName>
    <label>Monthly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Monthly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Recurring_Target__c</fullName>
    <label>Monthly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Target_Month_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Month_Date__c</fullName>
    <label>Target Month Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Weekly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_OTC_Target__c</fullName>
    <label>Weekly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Weekly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Recurring_Target__c</fullName>
    <label>Weekly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <description>*****************************************DO NOT MODIFY THIS FIELD*****************************************

This field is used to report on users and what market they are assigned to. Workflow Rules, Approval Processes and other customization&apos;s rely on this field. Changing any of this field&apos;s attributes will cause adverse reactions in the system. 

*****************************************DO NOT MODIFY THIS FIELD*****************************************</description>
    <label>Digicel Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>BVI</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>FWI</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Saint Kitts and Nevis</fullName>
            </value>
            <value>
                <fullName>Saint Lucia</fullName>
            </value>
            <value>
                <fullName>Saint Vincent and the Grenadines</fullName>
            </value>
            <value>
                <fullName>Suriname</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>Turks and Caicos Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Tonga</fullName>
            </value>
            <value>
                <fullName>Vanuatu</fullName>
            </value>
            <value>
                <fullName>Group Business Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ICT_Monthly_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>ICT_Monthly_Revenue_Target__c</fullName>
    <label>Total ICT Monthly Revenue Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Monthly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_OTC_Target__c</fullName>
    <label>Monthly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Monthly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Recurring_Target__c</fullName>
    <label>Monthly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Next_Month_ICT_Monthly_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Next_Month_ICT_Monthly_Revenue__c</fullName>
    <label>Next Month ICT Monthly Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Next_Month_Monthly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Next_Month_Monthly_OTC_Target__c</fullName>
    <label>Next Month Monthly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Next_Month_Monthly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Next_Month_Monthly_Recurring_Target__c</fullName>
    <label>Next Month Monthly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Next_Month_Weekly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Next_Month_Weekly_OTC_Target__c</fullName>
    <label>Next Month Weekly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Next_Month_Weekly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Next_Month_Weekly_Recurring_Target__c</fullName>
    <label>Next Month Weekly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Previous_Month_ICT_Monthly_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_ICT_Monthly_Revenue__c</fullName>
    <label>Previous Month ICT Monthly Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Previous_Month_Monthly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Monthly_OTC_Target__c</fullName>
    <label>Previous Month Monthly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Previous_Month_Monthly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Monthly_Recurring_Target__c</fullName>
    <label>Previous Month Monthly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Previous_Month_Weekly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Weekly_OTC_Target__c</fullName>
    <label>Previous Month Weekly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Previous_Month_Weekly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Weekly_Recurring_Target__c</fullName>
    <label>Previous Month Weekly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Weekly_OTC_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_OTC_Target__c</fullName>
    <label>Weekly OTC Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Weekly_Recurring_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Recurring_Target__c</fullName>
    <label>Weekly Recurring Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/classSummarizeMonthlyTarget.cls
global class classSummarizeMonthlyTarget implements Schedulable{
	global void execute(SchedulableContext SC) {
		List<User> listUser = [SELECT Id, ICT_Monthly_Revenue_Target__c,
								Monthly_Recurring_Target__c, Monthly_OTC_Target__c,
								Previous_Month_ICT_Monthly_Revenue__c,
								Previous_Month_Monthly_OTC_Target__c,
								Previous_Month_Monthly_Recurring_Target__c,
								Next_Month_ICT_Monthly_Revenue__c,
								Next_Month_Monthly_OTC_Target__c,
								Next_Month_Monthly_Recurring_Target__c,
								Weekly_OTC_Target__c,
								Weekly_Recurring_Target__c,
								Previous_Month_Weekly_OTC_Target__c,
								Previous_Month_Weekly_Recurring_Target__c,
								Next_Month_Weekly_OTC_Target__c,
								Next_Month_Weekly_Recurring_Target__c,
								Digicel_Country__c
								FROM User
								WHERE isActive = true];
		
		List<Monthly_ICT_GSM_Targets__c> listMonthlyTarget = [SELECT Id, Target_Month_Date__c,
															ICT_Monthly_Revenue_Target__c,
															Monthly_OCT__c,
															Monthly_Recurring_Target__c,
															Weekly_Recurring_Target__c,
															Weekly_OTC_Target__c,
															ICT_User_Target_Records__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.ICT_Monthly_Revenue_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Monthly_Recurring_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Monthly_OTC_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Previous_Month_ICT_Monthly_Revenue__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Previous_Month_Monthly_OTC_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Previous_Month_Monthly_Recurring_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Next_Month_ICT_Monthly_Revenue__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Next_Month_Monthly_OTC_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Next_Month_Monthly_Recurring_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Weekly_OTC_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Weekly_Recurring_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Previous_Month_Weekly_OTC_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Previous_Month_Weekly_Recurring_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Next_Month_Weekly_OTC_Target__c,
															ICT_User_Target_Records__r.ICT_Sales_Represenative__r.Next_Month_Weekly_Recurring_Target__c
															FROM Monthly_ICT_GSM_Targets__c
															WHERE ICT_User_Target_Records__r.ICT_Sales_Represenative__r.isActive = true
															AND (Target_Month_Date__c = THIS_MONTH
															OR Target_Month_Date__c = LAST_MONTH
															OR Target_Month_Date__c = NEXT_MONTH)];
		
		Map<Id, User> mapUser = new Map<Id, User>();
		for(User u: listUser){
			if(u.Digicel_Country__c != null && u.Digicel_Country__c.length()>0){
				u.ICT_Monthly_Revenue_Target__c = 0;
				u.Monthly_Recurring_Target__c = 0;
				u.Monthly_OTC_Target__c = 0;
				u.Previous_Month_ICT_Monthly_Revenue__c = 0;
				u.Previous_Month_Monthly_OTC_Target__c = 0;
				u.Previous_Month_Monthly_Recurring_Target__c = 0;
				u.Next_Month_ICT_Monthly_Revenue__c = 0;
				u.Next_Month_Monthly_OTC_Target__c = 0;
				u.Next_Month_Monthly_Recurring_Target__c = 0;
				
				u.Weekly_OTC_Target__c = 0;
				u.Weekly_Recurring_Target__c = 0;
				u.Previous_Month_Weekly_OTC_Target__c = 0;
				u.Previous_Month_Weekly_Recurring_Target__c = 0;
				u.Next_Month_Weekly_OTC_Target__c = 0;
				u.Next_Month_Weekly_Recurring_Target__c = 0;
				
				mapUser.put(u.Id, u);
			}
		}
		
		for(Monthly_ICT_GSM_Targets__c monthlyTarget: listMonthlyTarget){
			if(mapUser.containsKey(monthlyTarget.ICT_User_Target_Records__r.ICT_Sales_Represenative__c)){
				User u = mapUser.get(monthlyTarget.ICT_User_Target_Records__r.ICT_Sales_Represenative__c);
				
				if(monthlyTarget.Target_Month_Date__c!=null && monthlyTarget.Target_Month_Date__c.month() == System.today().month()){
					u.ICT_Monthly_Revenue_Target__c += (monthlyTarget.ICT_Monthly_Revenue_Target__c!=null?monthlyTarget.ICT_Monthly_Revenue_Target__c:0);
					u.Monthly_Recurring_Target__c += (monthlyTarget.Monthly_Recurring_Target__c!=null?monthlyTarget.Monthly_Recurring_Target__c:0);
					u.Monthly_OTC_Target__c += (monthlyTarget.Monthly_OCT__c!=null?monthlyTarget.Monthly_OCT__c:0);
					
					u.Weekly_Recurring_Target__c += (monthlyTarget.Weekly_Recurring_Target__c!=null?monthlyTarget.Weekly_Recurring_Target__c:0);
					u.Weekly_OTC_Target__c += (monthlyTarget.Weekly_OTC_Target__c!=null?monthlyTarget.Weekly_OTC_Target__c:0);
					
				}else if(monthlyTarget.Target_Month_Date__c!=null && monthlyTarget.Target_Month_Date__c.month() == System.today().addMonths(-1).month()){
					u.Previous_Month_ICT_Monthly_Revenue__c += (monthlyTarget.ICT_Monthly_Revenue_Target__c!=null?monthlyTarget.ICT_Monthly_Revenue_Target__c:0);
					u.Previous_Month_Monthly_Recurring_Target__c += (monthlyTarget.Monthly_Recurring_Target__c!=null?monthlyTarget.Monthly_Recurring_Target__c:0);
					u.Previous_Month_Monthly_OTC_Target__c += (monthlyTarget.Monthly_OCT__c!=null?monthlyTarget.Monthly_OCT__c:0);
					
					u.Previous_Month_Weekly_Recurring_Target__c += (monthlyTarget.Weekly_Recurring_Target__c!=null?monthlyTarget.Weekly_Recurring_Target__c:0);
					u.Previous_Month_Weekly_OTC_Target__c += (monthlyTarget.Weekly_OTC_Target__c!=null?monthlyTarget.Weekly_OTC_Target__c:0);
					
				} else if(monthlyTarget.Target_Month_Date__c!=null && monthlyTarget.Target_Month_Date__c.month() == System.today().addMonths(1).month()){
					u.Next_Month_ICT_Monthly_Revenue__c += (monthlyTarget.ICT_Monthly_Revenue_Target__c!=null?monthlyTarget.ICT_Monthly_Revenue_Target__c:0);
					u.Next_Month_Monthly_Recurring_Target__c += (monthlyTarget.Monthly_Recurring_Target__c!=null?monthlyTarget.Monthly_Recurring_Target__c:0);
					u.Next_Month_Monthly_OTC_Target__c += (monthlyTarget.Monthly_OCT__c!=null?monthlyTarget.Monthly_OCT__c:0);
					
					u.Next_Month_Weekly_Recurring_Target__c += (monthlyTarget.Weekly_Recurring_Target__c!=null?monthlyTarget.Weekly_Recurring_Target__c:0);
					u.Next_Month_Weekly_OTC_Target__c += (monthlyTarget.Weekly_OTC_Target__c!=null?monthlyTarget.Weekly_OTC_Target__c:0);
					
				}
				mapUser.put(u.Id, u);
			}
		}
		
		if(mapUser.size()>0) update mapUser.values();
	}
}