DigicielFull/force-app/main/default/objects/ICT_User_Target_Records__c/ICT_User_Target_Records__c.object-meta.xml
<CustomObject>
    <label>ICT User Target Records</label>
    <nameField>
        <displayFormat>User-{0000000}</displayFormat>
        <label>ICT User Target Records Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICT User Target Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICT_User_Target_Records__c/fields/ICT_Sales_Represenative__c.field-meta.xml
<CustomField>
    <fullName>ICT_Sales_Represenative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICT Sales Represenative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ICT_User_Target_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICT_User_Target_Records__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <formula>ICT_Sales_Represenative__r.FirstName &amp; &quot; &quot; &amp;  ICT_Sales_Represenative__r.LastName</formula>
    <label>User Name</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/Monthly_ICT_GSM_Targets__c.object-meta.xml
<CustomObject>
    <label>Monthly ICT &amp; GSM Targets</label>
    <nameField>
        <displayFormat>Digicel-{0000000}</displayFormat>
        <label>Monthly ICT &amp; GSM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly ICT &amp; GSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/ICT_Monthly_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>ICT_Monthly_Revenue_Target__c</fullName>
    <label>ICT Monthly Revenue Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/ICT_User_Target_Records__c.field-meta.xml
<CustomField>
    <fullName>ICT_User_Target_Records__c</fullName>
    <label>ICT User Target Records</label>
    <referenceTo>ICT_User_Target_Records__c</referenceTo>
    <relationshipLabel>Monthly ICT &amp; GSM Targets</relationshipLabel>
    <relationshipName>Monthly_ICT_GSM_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Target_Month_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Month_Date__c</fullName>
    <label>Target Month Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation_Log__c/Vacation_Log__c.object-meta.xml
<CustomObject>
    <label>Vacation Log</label>
    <nameField>
        <displayFormat>Vacation-{000000000}</displayFormat>
        <label>Vacation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Log</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation_Log__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacation_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Vacation_Log__c/fields/Vacation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_End_Date__c</fullName>
    <label>Vacation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation_Log__c/fields/Vacation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Start_Date__c</fullName>
    <label>Vacation Start Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/classes/testClassMonthlyTarget.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class testClassMonthlyTarget {

    static testMethod void myUnitTest() {
        ICT_User_Target_Records__c targetRecord = new ICT_User_Target_Records__c(
        		CurrencyIsoCode = UserInfo.getDefaultCurrency(),
        		ICT_Sales_Represenative__c = UserInfo.getUserId());
        
        insert targetRecord;
        
        Monthly_ICT_GSM_Targets__c monthlyTarget1 = new Monthly_ICT_GSM_Targets__c(
        		CurrencyIsoCode = UserInfo.getDefaultCurrency(),
        		ICT_Monthly_Revenue_Target__c = 100.00,
        		ICT_User_Target_Records__c = targetRecord.Id,
        		Target_Month_Date__c = System.today());
        insert monthlyTarget1;
        
        Monthly_ICT_GSM_Targets__c monthlyTarget2 = new Monthly_ICT_GSM_Targets__c(
        		CurrencyIsoCode = UserInfo.getDefaultCurrency(),
        		ICT_Monthly_Revenue_Target__c = 100.00,
        		ICT_User_Target_Records__c = targetRecord.Id,
        		Target_Month_Date__c = System.today().addMonths(1));
        insert monthlyTarget2;
        
        monthlyTarget2.Target_Month_Date__c = System.today();
        update monthlyTarget2;
        
        delete monthlyTarget2;
        
        Vacation_Log__c vacationLog = new Vacation_Log__c(
        		User_Name__c = Userinfo.getUserId(),
        		Vacation_Start_Date__c = System.today().addDays(-2),
        		Vacation_End_Date__c = System.today().addDays(1));
        insert vacationLog;
        
        Test.startTest();
        
        String CRON_EXP = '0 0 0 3 9 ? 2022';
	    String jobid = System.schedule('Prueba_FY', CRON_EXP, new classVerifyMonthlyTargetsFiscalYear());
	    CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
	    // Verify the expressions are the same  
	    System.assertEquals(CRON_EXP, ct.CronExpression);
	
	   	// Verify the job has not run  
	   	    
	    System.assertEquals(0, ct.TimesTriggered);
	    
	    String CRON_EXP_2 = '0 0 0 3 10 ? 2022';
	    String jobid_2 = System.schedule('Prueba_S', CRON_EXP_2, new classSummarizeMonthlyTarget());
	    CronTrigger ct_2 = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId_2];
	    // Verify the expressions are the same  
	    System.assertEquals(CRON_EXP_2, ct_2.CronExpression);
	
	   	// Verify the job has not run  
	   	    
	    System.assertEquals(0, ct_2.TimesTriggered);
	    
	    String CRON_EXP_3 = '0 0 0 3 11 ? 2022';
	    String jobid_3 = System.schedule('Prueba_VA', CRON_EXP_3, new classVacationStatusUpdate());
	    CronTrigger ct_3 = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId_3];
	    // Verify the expressions are the same  
	    System.assertEquals(CRON_EXP_3, ct_3.CronExpression);
	
	   	// Verify the job has not run  
	   	    
	    System.assertEquals(0, ct_3.TimesTriggered);
	    
	    vacationLog.Vacation_End_Date__c = System.today().addDays(-1);
	    update vacationLog;
        
        String CRON_EXP_4 = '0 0 0 3 12 ? 2022';
	    String jobid_4 = System.schedule('Prueba_VI', CRON_EXP_4, new classVacationStatusUpdate());
	    CronTrigger ct_4 = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId_4];
	    // Verify the expressions are the same  
	    System.assertEquals(CRON_EXP_4, ct_4.CronExpression);
	
	   	// Verify the job has not run  
	   	    
	    System.assertEquals(0, ct_4.TimesTriggered);
	    
        Test.stopTest();
    }
}