force-app/main/default/objects/Commission_Target__c/Commission_Target__c.object-meta.xml
<CustomObject>
    <label>Commission / Target</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions / Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Target__c/fields/Commission_Rate_per_Activation__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate_per_Activation__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commission Rate per Activation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Target__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Commission_Target__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digicel PNG, Digicel PNG Data Nets, Digicel PNG NEC, Digicel Nauru, Digicel Fiji, Digicel Vanuatu, Digicel Samoa, Digicel Tonga, Digicel PNG Remington</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Commissions / Targets</relationshipLabel>
    <relationshipName>Commissions_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Commission_Target__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Digicel_Country__c</field>
            <operation>equals</operation>
            <value>Fiji, PNG, Samoa, Vanuatu, Tonga, Nauru</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Commissions_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <businessOwnerGroup>SFDC_Admin_Team</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>functionality is no longer required</description>
    <label>zDeprecated - Monthly Target</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Monthly_ICT_GSM_Targets__c.ICT_User_Target_Records__r.ICT_Sales_Represenative__c</field>
            <operation>equals</operation>
            <valueField>$Source.OwnerId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Monthly_ICT_GSM_Targets__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/HIDDEN_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>HIDDEN_Product_Id__c</fullName>
    <label>Product Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/OpportunityLineItem/fields/Rate_per_Activation__c.field-meta.xml
<CustomField>
    <fullName>Rate_per_Activation__c</fullName>
    <label>Rate per Activation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/classes/OpportunityLineItemUpdate.cls
public class OpportunityLineItemUpdate{
    
    private static List<Commission_Target__c> ctList = new List<Commission_Target__c>(); 
    
    public static void setFields(List<OpportunityLineItem> OppLineItems){
    
    //Get the Product Id for each entry
    //Map<Id, String> productMap = new Map <Id, String>();
    Set<Id> productIds = new Set<Id>();
    Set<Id> userIds = new Set<Id>();
	
	List<Id> pricebookEntryIds = new List<Id>();
	List<Id> opportunityIds = new List<Id>();
	for(OpportunityLineItem opl: OppLineItems){
		pricebookEntryIds.add(opl.PricebookEntryId);
		opportunityIds.add(opl.OpportunityId);
	}
	
	Map<Id, PricebookEntry> mapPriceBookEntries = new Map<Id, PricebookEntry>([Select Id, Product2Id From PricebookEntry Where Id IN:pricebookEntryIds]);
	Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>([Select Id, OwnerId From Opportunity Where Id IN:opportunityIds]);
	
    for(OpportunityLineItem opl: OppLineItems){
    	if(mapPriceBookEntries.containsKey(opl.PricebookEntryId)){
	        opl.HIDDEN_Product_Id__c = mapPriceBookEntries.get(opl.PricebookEntryId).Product2Id;//productMap.get(opl.PricebookEntryId);
	        productIds.add(opl.HIDDEN_Product_Id__c);
    	}
    	if(mapOpportunities.containsKey(opl.OpportunityId)){
    		userIds.add(mapOpportunities.get(opl.OpportunityId).OwnerId);
    	}
    }
    
    //Check for matching Commissions and Targets
    ctList = [Select c.Sales_Representative__c, C.Monthly_Target__c, C.Id, c.Commission_Rate_per_Activation__c,
                c.Product__c From Commission_Target__c c Where c.Sales_Representative__c in:userIds AND c.Product__c in:productIds];
        
    //Set field values on the Line Items
    if(ctList.Size()>0){
        for(OpportunityLineItem oneOPL: OppLineItems){
          for(Commission_Target__c oneCT: ctList){
          	if(mapOpportunities.containsKey(oneOPL.OpportunityId)){
	            if(mapOpportunities.get(oneOPL.OpportunityId).OwnerId == oneCT.Sales_Representative__c && oneOPL.HIDDEN_Product_Id__c == oneCT.Product__c){
	              oneOPL.Rate_per_Activation__c = oneCT.Commission_Rate_per_Activation__c;
	              oneOPL.Monthly_Target__c = oneCT.Monthly_Target__c;
	            }
          	}
          }
        }
    }            
    } 
}