force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>ICT &amp; GSM Cross Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Contract/fields/PNG_Active__c.field-meta.xml
<CustomField>
    <fullName>PNG_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PNG_OpportunityContact__c.field-meta.xml
<CustomField>
    <fullName>PNG_OpportunityContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Contract/fields/PNG_Quote__c.field-meta.xml
<CustomField>
    <fullName>PNG_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>PNG_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Contract_Term_SP__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term_SP__c</fullName>
    <businessOwnerGroup>SFDC_Admin_Team</businessOwnerGroup>
    <inlineHelpText>What is the total duration of the Contract?

1 Year =  12

2 Years = 24

3 Years = 36

4 Years = 48

5 Years = 60</inlineHelpText>
    <label>Contract Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>zDeprecatedContract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Smartnet</fullName>
            </value>
            <value>
                <fullName>Broadband</fullName>
            </value>
            <value>
                <fullName>E1 Voice</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>IPLC</fullName>
            </value>
            <value>
                <fullName>DPLC</fullName>
            </value>
            <value>
                <fullName>GSM Gateway</fullName>
            </value>
            <value>
                <fullName>Office Phone</fullName>
            </value>
            <value>
                <fullName>Bundled Contract</fullName>
            </value>
            <value>
                <fullName>Online Back Up</fullName>
            </value>
            <value>
                <fullName>Hosted Exchange</fullName>
            </value>
            <value>
                <fullName>MDM</fullName>
            </value>
            <value>
                <fullName>M2M</fullName>
            </value>
            <value>
                <fullName>DAAS</fullName>
            </value>
            <value>
                <fullName>DRAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Opportunity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.No_Longer_with_Company__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PNG_QuoteType__c.field-meta.xml
<CustomField>
    <fullName>PNG_QuoteType__c</fullName>
    <formula>TEXT(Opportunity.PNG_OpportunityType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/classes/PNG_QuoteTriggerHelper.cls
public without sharing class PNG_QuoteTriggerHelper {
    
    public static void createContractRecord(Map<Id, Quote> newQuoteMap, Map<Id, Quote> oldQuoteMap){
        
        List<Quote> updatedQuotes=[select id,name,AccountID,OpportunityId,Opportunity.Opportunity_Contact__c,Opportunity.Contract_Term_SP__c,Status,RecordTypeId,PNG_QuoteType__c from Quote where id=:newQuoteMap.keySet() and RecordTypeId=:System.Label.PNG_ApprovedQuoteRecordType and Status =: System.Label.PNG_QStatusAccept];
        system.debug('Updated quotes '+ updatedQuotes);
        system.debug('Updated quotes size: '+ updatedQuotes.size());
                
        List<Contract> contractsList= new List<Contract>();
        
        if(updatedQuotes.size()>0){
        	
            for(Quote quote: updatedQuotes){
                if(oldQuoteMap.get(quote.Id).Status != Label.PNG_QStatusAccept){
                     contractsList.add(createNewContract(quote));
                }
            }
        }
        
        if(contractsList.size()>0){
            Database.insert(contractsList);
        }               
       
    }
        
    private static Contract createNewContract(Quote quote){
		
        Contract newContract = new Contract();
        newContract.RecordTypeId = Label.PNG_ContractRecordTypeId;					//Set PNG record type to contract
        newContract.Name = quote.Name + ' Contract';
        newContract.AccountId = quote.AccountId;
        newContract.Opportunity__c = quote.OpportunityId;
        newContract.Status = Label.PNG_ContractStatusDraft;    						//Set Contract status as draft     
        newContract.StartDate= Date.today();
        if(quote.Opportunity.Contract_Term_SP__c!=null){
            newContract.ContractTerm = quote.Opportunity.Contract_Term_SP__c.intValue();	//Set contract term from the opportunity
        }
        newContract.PNG_OpportunityContact__c = quote.Opportunity.Opportunity_Contact__c;	//Set opportunity contact
        newContract.PNG_Quote__c=quote.Id;
        newContract.PNG_Active__c=true;														//Make the contract active
        if(quote.PNG_QuoteType__c == Label.PNG_QTypeICT){
            newContract.Contract_Type__c = Label.PNG_QTypeICT;
        }
        else if(quote.PNG_QuoteType__c == Label.PNG_QTypeGSM){
            newContract.Contract_Type__c= Label.PNG_QTypeGSM;
        }
        else if(quote.PNG_QuoteType__c== System.Label.PNG_QTypeICTGSM){
            newContract.Contract_Type__c= System.Label.PNG_CTypeICTGSM;
        }
        system.debug('Contract: '+ newContract);
        
        return newContract;
    }
}