force-app/main/default/objects/Account/fields/PNG_Account_Level__c.field-meta.xml
<CustomField>
    <fullName>PNG_Account_Level__c</fullName>
    <label>Account Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/PNG_EntitlementLevel__c.field-meta.xml
<CustomField>
    <fullName>PNG_EntitlementLevel__c</fullName>
    <label>Entitlement Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Contract/recordTypes/PNG_Digicel_ICT_GSM.recordType-meta.xml
<RecordType>
    <fullName>PNG_Digicel_ICT_GSM</fullName>
    <active>true</active>
    <label>Digicel PNG ICT &amp; GSM</label>
</RecordType>

force-app/main/default/objects/Entitlement/fields/PNG_EntitlementType__c.field-meta.xml
<CustomField>
    <fullName>PNG_EntitlementType__c</fullName>
    <label>Entitlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Services</fullName>
            </value>
            <value>
                <fullName>Connectivity &amp; Enterprise Services</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Opportunity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.No_Longer_with_Company__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/PNG_OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>PNG_OpportunityType__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>ICT &amp; GSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PNG_ContractTriggerTestClass.cls
@isTest
public class PNG_ContractTriggerTestClass {
    
	static Id contractRecId = [Select id from RecordType where sObjectType = 'Contract' and developername ='PNG_Digicel_ICT_GSM' ].id ;
	
    @testSetup static void setup() {
        Account acc = new Account(Name='Test Acc1', Type='Customer');
        insert acc;
        Contact con = new Contact(AccountId=acc.Id, FirstName='Test',LastName='contact');
        insert con;
		Id oppRecId = [Select id from RecordType where sObjectType = 'Opportunity' and developername ='PNG_Digicel_ICT_GSM' ].id ;
        Opportunity opp= new Opportunity(RecordTypeId=oppRecId, Name = 'Test Opportunity',
                                         AccountId = acc.Id, Opportunity_Contact__c= con.Id,
                                         PNG_OpportunityType__c='ICT',
                                         StageName = 'Prospecting & Qualification', CloseDate = System.today()+10,
                                        Pricebook2Id = Test.getStandardPricebookId());
        insert opp;
    }
    
	@isTest
    public static void testGoldMobileServicesEntitlement(){
        
        Account acc = [SELECT Id, PNG_Account_Level__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Gold';
        update acc;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'GSM';
        update opp;
        Test.startTest();
        Contract cont = new Contract(RecordTypeId = contractRecId, Status ='PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        cont.Status='PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Gold');
    }
    @isTest
    public static void testGoldConnectivityEnterpriseEntitlement(){
        
        Account acc = [SELECT Id,PNG_Account_Level__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Gold';
        update acc;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'ICT';
        update opp;
        Test.startTest();
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        cont.Status='PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Gold');
    }
    @isTest
    public static void testSilverMobileServicesEntitlement(){
        
        Account acc = [SELECT Id, PNG_Account_Level__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Silver';
        update acc;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'GSM';
        update opp;
        Test.startTest();
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        cont.Status='PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Silver');
    }
    @isTest
    public static void testSilverConnectivityEnterpriseEntitlement(){
        
        Account acc = [SELECT Id,PNG_Account_Level__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Silver';
        update acc;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'ICT';
        update opp;
        Test.startTest();
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        cont.Status='PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Silver');
    }
        @isTest
    public static void testBronzeMobileServicesEntitlement(){
        
        Account acc = [SELECT Id, PNG_Account_Level__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Bronze';
        update acc;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'GSM';
        update opp;
        Test.startTest();
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        cont.Status='PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Bronze');
    }
    @isTest
    public static void testBronzeConnectivityEnterpriseEntitlement(){
        
        Account acc = [SELECT Id,PNG_Account_Level__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Bronze';
        update acc;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'ICT';
        update opp;
        Test.startTest();
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        cont.Status='PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Bronze');
    }
     @isTest
    public static void testDeactivateExistingEntitlement(){
        
        Account acc = [SELECT Id,PNG_Account_Level__c,PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Bronze';
        acc.PNG_EntitlementLevel__c ='Silver';
        update acc;
        Entitlement ent = new Entitlement(Name ='Test entitlement',AccountId = acc.Id,StartDate=System.today()-1);
        insert ent;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'ICT';
        update opp;
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id);
        insert cont;
        Test.startTest();
        cont.Status = 'PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Bronze');
    }
    @isTest
    public static void testUpdateExistingGSMEntitlement(){
        
        Account acc = [SELECT Id,PNG_Account_Level__c,PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Bronze';
        acc.PNG_EntitlementLevel__c ='Bronze';
        update acc;
        Entitlement ent = new Entitlement(Name ='Test entitlement',AccountId = acc.Id, StartDate=System.today()-8,
                                          PNG_EntitlementType__c = 'Mobile Services',EndDate=System.today()+1);
        insert ent;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'GSM';
        update opp;
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id, StartDate=System.today()-10,ContractTerm=1);
        insert cont;
        Test.startTest();
        cont.Status = 'PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Bronze');
    }
    @isTest
    public static void testUpdateExistingICTEntitlement(){
        
        Account acc = [SELECT Id,PNG_Account_Level__c,PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        acc.PNG_Account_Level__c = 'Bronze';
        acc.PNG_EntitlementLevel__c ='Bronze';
        update acc;
        Entitlement ent = new Entitlement(Name ='Test entitlement',AccountId = acc.Id, StartDate=System.today()-8,
                                          PNG_EntitlementType__c = 'Connectivity & Enterprise',EndDate=System.today()+1);
        insert ent;
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name= 'Test Opportunity' LIMIT 1];
        opp.PNG_OpportunityType__c = 'ICT';
        update opp;
        Contract cont = new Contract(RecordTypeId = contractRecId, Status = 'PNG_Customer_Signed_Approved',
                                    AccountID = acc.Id, Opportunity__c = opp.Id, StartDate=System.today()-10,ContractTerm=1);
        insert cont;
        Test.startTest();
        cont.Status = 'PNG_Contract mutually signed';
        update cont;
        Test.stopTest();
        Account updatedAcc = [SELECT Id, PNG_EntitlementLevel__c FROM Account WHERE Name='Test Acc1' LIMIT 1];
        System.assertEquals(updatedAcc.PNG_EntitlementLevel__c, 'Bronze');
    }
}