force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/InvoiceID__c.field-meta.xml
<CustomField>
    <fullName>InvoiceID__c</fullName>
    <externalId>true</externalId>
    <label>Invoice ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

DigicielFull/force-app/main/default/classes/InvoiceKaldom_QUE.cls
public with sharing class InvoiceKaldom_QUE implements Queueable, Database.AllowsCallouts  {
    List<Invoice__c> lstInvoiceToUpsert = new List<Invoice__c>();
    
    public InvoiceKaldom_QUE(List<Invoice__c> lstInvoiceForOneAcc) {
        lstInvoiceToUpsert = lstInvoiceForOneAcc;
    }

    public void execute(QueueableContext context) {
        try {
            database.upsert(lstInvoiceToUpsert, Invoice__c.InvoiceID__c, true);      
        } catch(DmlException e) {
            System.debug('Exception sur l\'upsert des factures: ' + e.getMessage());
        }   
    }       
}