DigicielFull/force-app/main/default/objects/Contract/fields/PNG_Quote__c.field-meta.xml
<CustomField>
    <fullName>PNG_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>PNG_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Contract_Term_SP__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term_SP__c</fullName>
    <businessOwnerGroup>SFDC_Admin_Team</businessOwnerGroup>
    <inlineHelpText>What is the total duration of the Contract?

1 Year =  12

2 Years = 24

3 Years = 36

4 Years = 48

5 Years = 60</inlineHelpText>
    <label>Contract Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Opportunity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.No_Longer_with_Company__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/PNG_OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>PNG_OpportunityType__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>ICT &amp; GSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/PNG_QuoteType__c.field-meta.xml
<CustomField>
    <fullName>PNG_QuoteType__c</fullName>
    <formula>TEXT(Opportunity.PNG_OpportunityType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/classes/PNG_QuoteTriggerHelperTest.cls
@isTest
public class PNG_QuoteTriggerHelperTest {
    @isTest
    public static void createContractRecordTest(){
        Account acc= new Account();
        acc.Name='New Test Account';
        acc.Type='Customer';
        insert acc;
        Contact con=new Contact();
        con.FirstName='New';
        con.LastName='Test Contact';
        con.AccountId=acc.Id;
        insert con;
        
        List<Opportunity> opportunities= new List<Opportunity>();
        List<Quote> quotes= new List<Quote>();
        
        Opportunity opp1= new Opportunity();
        opp1.RecordTypeId=System.Label.PNG_OpprtunityRecordTypeId;
        opp1.Name ='New Test Opportunity: 1';
        opp1.AccountId=acc.Id;
        opp1.StageName='Prospecting & Qualification';
        opp1.CloseDate=System.today()+15;
        opp1.PNG_OpportunityType__c=System.Label.PNG_QTypeICT;
        opp1.Contract_Term_SP__c=12;
        opp1.Opportunity_Contact__c=con.Id;
        opportunities.add(opp1);
        
        Opportunity opp2= new Opportunity();
        opp2.RecordTypeId=System.Label.PNG_OpprtunityRecordTypeId;
        opp2.Name ='New Test Opportunity: 2';
        opp2.AccountId=acc.Id;
        opp2.StageName='Prospecting & Qualification';
        opp2.CloseDate=System.today()+10;
        opp2.PNG_OpportunityType__c=System.Label.PNG_QTypeGSM;
        opp2.Contract_Term_SP__c=12;
        opp2.Opportunity_Contact__c=con.Id;
        opportunities.add(opp2);
        
        Opportunity opp3= new Opportunity();
        opp3.RecordTypeId=System.Label.PNG_OpprtunityRecordTypeId;
        opp3.Name ='New Test Opportunity: 3';
        opp3.AccountId=acc.Id;
        opp3.StageName='Prospecting & Qualification';
        opp3.CloseDate=System.today()+10;
        opp3.PNG_OpportunityType__c=System.Label.PNG_QTypeICTGSM;
        opp3.Contract_Term_SP__c=12;
        opp3.Opportunity_Contact__c=con.Id;
        opportunities.add(opp3);
        insert opportunities;
        
        Quote quote1=new Quote();
        quote1.RecordTypeId=System.Label.PNG_QuoteRecordTypeId;
        quote1.Name='Test Quote : 1';
        quote1.OpportunityId=opp1.Id;
        quote1.Status='Draft';
        quotes.add(quote1);
        
        Quote quote2=new Quote();
        quote2.RecordTypeId=System.Label.PNG_QuoteRecordTypeId;
        quote2.Name='Test Quote : 2';
        quote2.OpportunityId=opp2.Id;
        quote2.Status='Approved';
        quote2.RecordTypeId=System.Label.PNG_ApprovedQuoteRecordType;
        quotes.add(quote2);
        
        Quote quote3=new Quote();
        quote3.RecordTypeId=System.Label.PNG_QuoteRecordTypeId;
        quote3.Name='Test Quote : 3';
        quote3.OpportunityId=opp3.Id;
        quote3.Status='Draft';
        quotes.add(quote3);
        insert quotes;
        System.debug('Quotes type:'+ quote3.PNG_QuoteType__c);
        
        quote1.Status='Needs Review';
        update quote1;
        quote1.Status='In Technical Feasibility Check';
        update quote1;
        quote1.Status='Technical Feasibility Approved';
        update quote1;
        quote1.Status='In Solution Review';
        update quote1;
        quote1.Status='Solution Approved';
        update quote1;
        quote1.Status='Approved';
        quote1.RecordTypeId=System.Label.PNG_ApprovedQuoteRecordType;
        update quote1;
    
        quote3.Status='Needs Review';
        update quote3;
        quote3.Status='In Technical Feasibility Check';
        update quote3;
        quote3.Status='Technical Feasibility Approved';
        update quote3;
        quote3.Status='In Solution Review';
        update quote3;
        quote3.Status='Solution Approved';
        update quote3;
        quote3.Status='Approved';
        quote3.RecordTypeId=System.Label.PNG_ApprovedQuoteRecordType;
        update quote3;
        
        Test.startTest();
        quote1.Status='Accepted';
        update quote1;
        System.assertNotEquals(null,quote1.OpportunityId);
        System.assertNotEquals(null,[select id, name,PNG_Quote__c from Contract where PNG_Quote__c=:quote1.id]);
        
        quote2.Status='Accepted';
        update quote2;
        System.assertNotEquals(null,quote2.OpportunityId);
        System.assertNotEquals(null,[select id, name,PNG_Quote__c from Contract where PNG_Quote__c=:quote2.id]);
       
        quote3.Status='Accepted';
        update quote3;
        System.assertNotEquals(null,quote3.OpportunityId);
        System.assertNotEquals(null,[select id, name,PNG_Quote__c from Contract where PNG_Quote__c=:quote3.id]);
        Test.stopTest();
  
    }
}