DigicielFull/force-app/main/default/objects/Opportunity/fields/Customer_Deposit_Waived__c.field-meta.xml
<CustomField>
    <fullName>Customer_Deposit_Waived__c</fullName>
    <description>Apex Class
https://na52.salesforce.com/01pd0000002XBPJ?retURL=%2Fp%2Fsetup%2Flayout%2FLayoutFieldList%3Ftype%3DOpportunity%26setupid%3DOpportunityFields</description>
    <formula>if( Account.Deposits_Waived__c == TRUE, &quot;Yes&quot;, &quot;No&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If &apos;Yes&apos; then the total deposit will be automatically set to 0</inlineHelpText>
    <label>z Deprecated - Customer Deposit Waived?</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Total_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposit__c</fullName>
    <description>This value is automatically calculated based on the total deposit for each product.</description>
    <label>Total Deposit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Total_Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Recurring_Revenue__c</fullName>
    <inlineHelpText>(Monthly Fee * 12)
This value is automatically calculated based on the total monthly fee for each product</inlineHelpText>
    <label>12 Month Recurring Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Deposit_Waived__c.field-meta.xml
<CustomField>
    <fullName>Customer_Deposit_Waived__c</fullName>
    <formula>if( Opportunity.Account.Deposits_Waived__c = TRUE, &quot;Yes&quot;, &quot;No&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Deposit Waived?</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Quote/fields/Total_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposit__c</fullName>
    <description>This value is automatically calculated based on the total deposit for each product.</description>
    <label>Total Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Quote/fields/Total_Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Recurring_Revenue__c</fullName>
    <description>(Monthly Fee * 12) This value is automatically calculated based on the total monthly fee for each product</description>
    <label>Total Recurring Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/FORMULA_Deposit__c.field-meta.xml
<CustomField>
    <fullName>FORMULA_Deposit__c</fullName>
    <formula>OpportunityLineItem.FORMULA_Deposit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/QuoteLineItem/fields/FORMULA_Monthly_Fee__c.field-meta.xml
<CustomField>
    <fullName>FORMULA_Monthly_Fee__c</fullName>
    <formula>if ( OpportunityLineItem.FORMULA_Monthly_Fee__c&gt;0 , OpportunityLineItem.FORMULA_Monthly_Fee__c , PricebookEntry.Product2.Monthly_Fee__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/QuoteLineItem/fields/Total_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposit__c</fullName>
    <formula>if( FORMULA_Deposit__c &gt;0, FORMULA_Deposit__c * Quantity , 0)</formula>
    <label>Total Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/classes/QuoteUpdate.cls
public with sharing class QuoteUpdate{

    private static Decimal deposit = 0;
    private static Decimal monthlyFee = 0;
    private static List<Quote> quoteList = new List<Quote>();
    private static List<Quote> quotesToBeUpdated = new List<Quote>();
    private static List<QuoteLineItem> oppLineItemsList = new List<QuoteLineItem>();
    private static Set<Id> finalQuoteIdsToUpdate = new Set<Id>();
    
    public static void setQuoteTotals(List<QuoteLineItem> quoteLineItems){
    
    //Get the Quote Ids
    Set<Id> quoteIds = new Set<Id>();
    for(QuoteLineItem qli: quoteLineItems){
        quoteIds.add(qli.QuoteId);
    }
    
    //Get a list of Quotes and their Line Items
    quoteList = [Select q.Id, q.Customer_Deposit_Waived__c From Quote q Where q.Id in: quoteIds];
    oppLineItemsList = [Select q.Id, q.QuoteId, q.FORMULA_Monthly_Fee__c, q.FORMULA_Deposit__c, q.Quantity
                        From QuoteLineItem q Where q.QuoteId in: quoteList];
                        
    //Get the vaues from the Line Items and sum them up to the Opportunity
    for(Quote oneQuote: quoteList){
        for(QuoteLineItem oneQLI: oppLineItemsList){
            if(oneQLI.QuoteId == oneQuote.Id){
              //Monthly Fee
              if(oneQLI.FORMULA_Monthly_Fee__c != null){
                system.debug('### monthlyFee  = ' + oneQLI.FORMULA_Monthly_Fee__c);
                system.debug('### Quantity = ' + oneQLI.Quantity);
                Decimal tmpMonthlyFee = (oneQLI.FORMULA_Monthly_Fee__c * oneQLI.Quantity) * 12;
                monthlyFee += tmpMonthlyFee;
                system.debug('### Total monthlyFee = ' + tmpMonthlyFee);  
              }
              
              //Deposit
              if(oneQLI.FORMULA_Deposit__c != null){
                system.debug('### Deposit  = ' + oneQLI.FORMULA_Deposit__c);  
                system.debug('### Quantity = ' + oneQLI.Quantity);
                Decimal tmpDeposit = oneQLI.FORMULA_Deposit__c * oneQLI.Quantity;
                deposit += tmpDeposit;
                system.debug('### Total Deposit = ' + deposit);
              }
            }
        }
        //Check if deposit is waived for this customer and then set all totals
        if(oneQuote.Customer_Deposit_Waived__c == 'No'){
            oneQuote.Total_Deposit__c = deposit;
        }
        else{
            oneQuote.Total_Deposit__c = 0;
        }
        
        oneQuote.Total_Recurring_Revenue__c = monthlyFee;
        
        /*Add Quote to the list for update - 
          we need to put a check in place to make sure we are not adding the same Id twice*/
        if(!finalQuoteIdsToUpdate.contains(oneQuote.Id)){
          finalQuoteIdsToUpdate.add(oneQuote.Id);  
          quotesToBeUpdated.add(oneQuote);
        }
    }
    //Update Quotes
    if(quotesToBeUpdated.size()>0){
      upsert quotesToBeUpdated;
    }
    
    }
}