DigicielFull/force-app/main/default/objects/Custom_Chart__c/Custom_Chart__c.object-meta.xml
<CustomObject>
    <label>Custom Chart</label>
    <nameField>
        <label>Custom Chart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Charts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Custom_Chart__c/fields/Base_Object__c.field-meta.xml
<CustomField>
    <fullName>Base_Object__c</fullName>
    <description>Base Object for the chart.</description>
    <label>Base Object</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart__c/fields/Base_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Base_Object_API_Name__c</fullName>
    <description>Base Object API Name for query of chart data.</description>
    <label>Base Object API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Chart__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Chart__c/fields/Source_Report__c.field-meta.xml
<CustomField>
    <fullName>Source_Report__c</fullName>
    <label>Source Report</label>
    <type>Url</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bar Chart</fullName>
                <default>true</default>
                <label>Bar Chart</label>
            </value>
            <value>
                <fullName>Column Chart</fullName>
            </value>
            <value>
                <fullName>Line Chart</fullName>
            </value>
            <value>
                <fullName>Pie Chart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/Custom_Chart_Field__c.object-meta.xml
<CustomObject>
    <label>Custom Chart Field</label>
    <nameField>
        <label>Custom Chart Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Chart Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Chart_Field_Number__c.field-meta.xml
<CustomField>
    <fullName>Chart_Field_Number__c</fullName>
    <label>Chart Field Number</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Condition_Value__c.field-meta.xml
<CustomField>
    <fullName>Condition_Value__c</fullName>
    <label>Condition Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Chart_Field__c/fields/Custom_Chart__c.field-meta.xml
<CustomField>
    <fullName>Custom_Chart__c</fullName>
    <label>Custom Chart</label>
    <referenceTo>Custom_Chart__c</referenceTo>
    <relationshipLabel>Custom Chart Fields</relationshipLabel>
    <relationshipName>Custom_Chart_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Custom_Chart_Field_Number_A__c.field-meta.xml
<CustomField>
    <fullName>Custom_Chart_Field_Number_A__c</fullName>
    <label>Custom Chart Field Number A</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Custom_Chart_Field_Number_B__c.field-meta.xml
<CustomField>
    <fullName>Custom_Chart_Field_Number_B__c</fullName>
    <label>Custom Chart Field Number B</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Custom_Chart_Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Custom_Chart_Related_Object__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Custom Chart Related Object</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The related object must belong to the same custom chart.</errorMessage>
        <filterItems>
            <field>Custom_Chart_Related_Object__c.Custom_Chart__c</field>
            <operation>equals</operation>
            <valueField>$Source.Custom_Chart__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Custom_Chart_Related_Object__c</referenceTo>
    <relationshipLabel>Custom Chart Fields</relationshipLabel>
    <relationshipName>Custom_Chart_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Chart_Field__c/fields/Display_Color__c.field-meta.xml
<CustomField>
    <fullName>Display_Color__c</fullName>
    <label>Display Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field_Use__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Aqua</fullName>
                <default>true</default>
                <label>Aqua</label>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Cyan</fullName>
            </value>
            <value>
                <fullName>Dark Blue</fullName>
            </value>
            <value>
                <fullName>Dark Green</fullName>
            </value>
            <value>
                <fullName>Dark Red</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Lime</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Display_Color_Hex_Code__c.field-meta.xml
<CustomField>
    <fullName>Display_Color_Hex_Code__c</fullName>
    <formula>CASE(TEXT(Display_Color__c), &quot;Aqua&quot;, &quot;00FFFF&quot;, &quot;Blue&quot;, &quot;0000FF&quot;, &quot;Brown&quot;, &quot;A52A2A&quot;, &quot;Cyan&quot;, &quot;00FFFF&quot;, &quot;Dark Blue&quot;, &quot;00008B&quot;, &quot;Dark Green&quot;, &quot;006400&quot;, &quot;Dark Red&quot;, &quot;8B0000&quot;, &quot;Gray&quot;, &quot;808080&quot;, &quot;Green&quot;, &quot;008000&quot;, &quot;Lime&quot;, &quot;00FF00&quot;, &quot;Orange&quot;, &quot;FFA500&quot;, &quot;Pink&quot;, &quot;FFC0CB&quot;, &quot;Purple&quot;, &quot;800080&quot;, &quot;Red&quot;, &quot;FF0000&quot;, &quot;Yellow&quot;, &quot;FFFF00&quot;, &quot;0000FF&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Color Hex Code</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Display_On_Chart__c.field-meta.xml
<CustomField>
    <fullName>Display_On_Chart__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display On Chart</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Display_Order_By__c.field-meta.xml
<CustomField>
    <fullName>Display_Order_By__c</fullName>
    <label>Display Order By</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Chart_Field__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Chart_Field__c/fields/Field_Use__c.field-meta.xml
<CustomField>
    <fullName>Field_Use__c</fullName>
    <label>Field Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Group By</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Condition</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/In_Not_In_Values__c.field-meta.xml
<CustomField>
    <fullName>In_Not_In_Values__c</fullName>
    <label>In / Not In Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Is_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Is_Date_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Date Field</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Field__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Subtract</fullName>
            </value>
            <value>
                <fullName>Multiply</fullName>
            </value>
            <value>
                <fullName>Divide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Chart_Field__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of summary field.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field_Use__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
            <value>
                <fullName>Minimum</fullName>
            </value>
            <value>
                <fullName>Maximum</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not Equals</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Greater Than or Equal</fullName>
            </value>
            <value>
                <fullName>Less Than or Equal</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Not In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Custom_Chart_Related_Object__c/Custom_Chart_Related_Object__c.object-meta.xml
<CustomObject>
    <label>Custom Chart Related Object</label>
    <nameField>
        <label>Custom Chart Related Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Chart Related Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Custom_Chart_Related_Object__c/fields/Custom_Chart__c.field-meta.xml
<CustomField>
    <fullName>Custom_Chart__c</fullName>
    <label>Custom Chart</label>
    <referenceTo>Custom_Chart__c</referenceTo>
    <relationshipLabel>Custom Chart Related Objects</relationshipLabel>
    <relationshipName>Custom_Chart_Related_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Chart_Related_Object__c/fields/Related_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_API_Name__c</fullName>
    <label>Related Object API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/classes/controllerCustomChart.cls
public with sharing class controllerCustomChart {
    private Custom_Chart__c customChart = new Custom_Chart__c();
    
    public controllerCustomChart(){
        displayChart = false;
        init();
    } 
    
    public void init(){
        String customChartCode = '';
        if(ApexPages.currentPage().getUrl().contains('_')){
            customChartCode = ApexPages.currentPage().getUrl().substring(ApexPages.currentPage().getUrl().indexOf('_')+1, ApexPages.currentPage().getUrl().indexOf('_')+5);
        }
        System.debug('Custom Chart Code: '+customChartCode);
        if(customChartCode.length() > 0){
            try{
                this.customChart = [Select c.Type__c, c.Source_Report__c, c.Name, c.Id, 
                                    c.Base_Object__c, c.Base_Object_API_Name__c, Width__c, Height__c,
                                    CurrencyIsoCode,
                                    (Select Id, Name, Related_Object_API_Name__c, Custom_Chart__c 
                                    From Custom_Chart_Related_Objects__r), 
                                    (Select Id, Name, Field_API_Name__c, Type__c, Field_Use__c, 
                                    Custom_Chart_Related_Object__c, Custom_Chart__c, Condition_Value__c, 
                                    Custom_Chart_Related_Object__r.Related_Object_API_Name__c, Display_Color__c, 
                                    Display_Color_Hex_Code__c, Display_On_Chart__c, Chart_Field_Number__c,
                                    Custom_Chart_Field_Number_A__c, Custom_Chart_Field_Number_B__c, Operator__c,
                                    In_Not_In_Values__c, Is_Date_Field__c, Display_Order_By__c
                                    From Custom_Chart_Fields__r Order By Chart_Field_Number__c asc) 
                                    From Custom_Chart__c c Where Code__c =: customChartCode limit 1];
            }catch(System.Exception e){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'The custom chart code ('+ customChartCode +') does not exist, please contact your admin.'));
            }
        }else{
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'No custom chart code was recovered, please contact your admin.'));
        }
        
        if(customChart.Id != null){ 
            chartURL = classCustomChart.buildImageURL(customChart);
            if(chartURL.length() > 0 ) displayChart = true;
        }
        //return null;
    }
    
    public String getCustomChartSource(){
        return this.customChart.Source_Report__c;
    }
    // The URL that renders the Google Chart
    public String chartURL { get; set; }  
    
    // Indicates whether the chart should be displayed 
    public Boolean displayChart { get; set; }
    
}