DigicielFull/force-app/main/default/objects/Pre_Sales_Request__c/Pre_Sales_Request__c.object-meta.xml
<CustomObject>
    <description>Pre Sales request</description>
    <label>Pre Sales Request</label>
    <nameField>
        <displayFormat>PSR-{000000000}</displayFormat>
        <label>Pre Sales Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Sales Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Pre_Sales_Request__c/recordTypes/Pre_Sales_Request.recordType-meta.xml
<RecordType>
    <fullName>Pre_Sales_Request</fullName>
    <active>true</active>
    <label>Pre Sales Request</label>
</RecordType>

DigicielFull/force-app/main/default/objects/Pre_Sales_Update__c/Pre_Sales_Update__c.object-meta.xml
<CustomObject>
    <label>Pre Sales Update</label>
    <nameField>
        <label>Pre Sales Update Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre Sales Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Sales_Update__c/fields/Pre_Sales_Request__c.field-meta.xml
<CustomField>
    <fullName>Pre_Sales_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre Sales Request</label>
    <referenceTo>Pre_Sales_Request__c</referenceTo>
    <relationshipLabel>Pre Sales Updates</relationshipLabel>
    <relationshipName>Pre_Sales_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Pre_Sales_Update__c/fields/Pre_Sales_Update__c.field-meta.xml
<CustomField>
    <fullName>Pre_Sales_Update__c</fullName>
    <label>Pre Sales Update</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Pre_Sales_Update__c/recordTypes/Pre_Sales_Update.recordType-meta.xml
<RecordType>
    <fullName>Pre_Sales_Update</fullName>
    <active>true</active>
    <label>Pre Sales Update</label>
</RecordType>

force-app/main/default/classes/redirectPreSalesUpdateController.cls
/*This class is a controller of PreSalesUpdateCreation Visualforce Page.
 Function: The Name field of Pre_Sales_Update object must be populated with the Pre_Sales_Request Name 
 plus the Current Date.*/
 
public class redirectPreSalesUpdateController{

    private Apexpages.Standardcontroller stdController; 
    
    public redirectPreSalesUpdateController(Apexpages.Standardcontroller stdController){
        this.stdController = stdController;
    }
    
    public String getPreSalesRequestLandingPage()
    {
         Schema.DescribeSObjectResult result = Pre_Sales_Request__c.SObjectType.getDescribe();
         return '/' + result.getKeyPrefix() + '/o';
    }
    
    //Retrieve Pre_Sales_Request Name and Redirect to Pre_Sales_Update Name Standard Page Layout
    public PageReference redirectPreSalesUpdate(){
        PageReference currPage = new PageReference(Apexpages.currentPage().getParameters().get('currentPageURL'));
        String url = '/'+Schema.getGlobalDescribe().get('Pre_Sales_Update__c').getDescribe().getKeyPrefix()+'/e?';
        for(String mapKey : currPage.getParameters().keySet()){
            if(mapKey!='save_new'){
                String mapValue = (mapKey!='sfdc.override'?currPage.getParameters().get(mapKey):'0');
                mapValue = mapValue.replace(' ', '%2B');
                 mapValue = mapValue.replace('/', '%2F');
                 mapValue = mapValue.replace('&', '%2526');
                url += (url.contains('=')?'&':'') + mapKey +'='+mapValue;
            }
         }
         //Retrieve Current Date, redirect and concatenate to Pre_Sales_Update Name of Page Layout
         String psrId = currPage.getParameters().get('retUrl').replace('/','');
         if (psrId.contains('?')) psrId = psrId.subString(0,psrId.indexOf('?'));
         String psrName = [Select Name From Pre_Sales_Request__c Where Id=:psrId].Name;
         Datetime currentDate = Datetime.now();
         String currentDateStr = currentDate.format('dd-MM-yyyy');
         url += '&nooverride=1';
         String name = psrName + ' - ' + currentDateStr;
         if(name.length() > 80) name = psrName.substring(0,67) + ' - ' + currentDateStr;
         url += '&Name=' + name;    
         PageReference redirectPage = new Pagereference(url);
         redirectPage.setRedirect(true);
         return redirectPage;
      }
}