DigicielFull/force-app/main/default/objects/User/fields/Vacation_Status__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Status__c</fullName>
    <label>Vacation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Vacation</fullName>
            </value>
            <value>
                <fullName>Not On Vacation</fullName>
                <default>true</default>
                <label>Not On Vacation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacation_Log__c/Vacation_Log__c.object-meta.xml
<CustomObject>
    <label>Vacation Log</label>
    <nameField>
        <displayFormat>Vacation-{000000000}</displayFormat>
        <label>Vacation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Log</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation_Log__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vacation_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Vacation_Log__c/fields/Vacation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_End_Date__c</fullName>
    <label>Vacation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation_Log__c/fields/Vacation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Start_Date__c</fullName>
    <label>Vacation Start Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/classes/classVacationStatusUpdate.cls
global class classVacationStatusUpdate implements Schedulable{
	global void execute(SchedulableContext SC) {
		List<User> listUsers = [SELECT Id, Vacation_Status__c FROM User
								WHERE Id IN (SELECT User_Name__c 
											FROM Vacation_Log__c
											WHERE (Vacation_Start_Date__c >= TODAY
											AND Vacation_End_Date__c <= TODAY
											AND User_Name__r.Vacation_Status__c = 'Not On Vacation')
											OR (((Vacation_Start_Date__c < TODAY
											AND Vacation_End_Date__c < TODAY)
											OR Vacation_Start_Date__c > TODAY)
											AND User_Name__r.Vacation_Status__c = 'On Vacation')
											)
								];
								
		for(User u: listUsers){
			if(u.Vacation_Status__c == 'On Vacation'){
				u.Vacation_Status__c = 'Not On Vacation';
			}else{
				u.Vacation_Status__c = 'On Vacation';
			}
		}
		if(listUsers.size()>0) update listUsers;
	}
}