DigicielFull/force-app/main/default/objects/Account/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specialterms__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/INFOLEGALERating__c.field-meta.xml
<CustomField>
    <fullName>INFOLEGALERating__c</fullName>
    <label>Infolegale Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/TelesoftNumber__c.field-meta.xml
<CustomField>
    <fullName>TelesoftNumber__c</fullName>
    <label>N° DBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

DigicielFull/force-app/main/default/objects/Opportunity/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
                <default>true</default>
                <label>30 %</label>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>La Reunion</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Mayotte</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Nouvelle Caledonie</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Saint Barthelemy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Estimated_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Billed_Date__c</fullName>
    <label>Estimated Billed Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/INFOLEGALERating__c.field-meta.xml
<CustomField>
    <fullName>INFOLEGALERating__c</fullName>
    <label>INFOLEGALE Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Networking</fullName>
            </value>
            <value>
                <fullName>Amda</fullName>
            </value>
            <value>
                <fullName>Audio Conferencing</fullName>
            </value>
            <value>
                <fullName>Avaya Unified Communication</fullName>
            </value>
            <value>
                <fullName>BIA ( Basic Internet Access)</fullName>
            </value>
            <value>
                <fullName>Broadband internet</fullName>
            </value>
            <value>
                <fullName>Bulk SMS</fullName>
            </value>
            <value>
                <fullName>Business Broadband</fullName>
            </value>
            <value>
                <fullName>Business in a Box</fullName>
            </value>
            <value>
                <fullName>Cisco Unified Communication</fullName>
            </value>
            <value>
                <fullName>Cloud Back-Up</fullName>
            </value>
            <value>
                <fullName>Cloud Backup SB</fullName>
            </value>
            <value>
                <fullName>Cloud Computing</fullName>
            </value>
            <value>
                <fullName>Cloud - DaaS</fullName>
            </value>
            <value>
                <fullName>Cloud - DRaaS</fullName>
            </value>
            <value>
                <fullName>Cloud - Hosted Email</fullName>
            </value>
            <value>
                <fullName>Cloud - IaaS</fullName>
            </value>
            <value>
                <fullName>Cloud - LoB hosting</fullName>
            </value>
            <value>
                <fullName>Cloud - MDM</fullName>
            </value>
            <value>
                <fullName>Cloud - NFV</fullName>
            </value>
            <value>
                <fullName>Cloud - PaaS</fullName>
            </value>
            <value>
                <fullName>Cloud - Private Cloud</fullName>
            </value>
            <value>
                <fullName>Cloud - Security</fullName>
            </value>
            <value>
                <fullName>Cloud Services</fullName>
            </value>
            <value>
                <fullName>Cloud - Storage &amp; Backup</fullName>
            </value>
            <value>
                <fullName>Cloud Telephony</fullName>
            </value>
            <value>
                <fullName>Cloud V1 Hosted Email</fullName>
            </value>
            <value>
                <fullName>Co-Location</fullName>
            </value>
            <value>
                <fullName>Connectivity Services</fullName>
            </value>
            <value>
                <fullName>CPE – Customer Premise Equipment</fullName>
            </value>
            <value>
                <fullName>Data VPN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SaleType__c.field-meta.xml
<CustomField>
    <fullName>SaleType__c</fullName>
    <inlineHelpText>New: Customers who have no services with Digicel should be tagged as &quot;New Customer&quot;

Existing: Customer who have services with Digicel should be tagged as &quot;Exisitng Customer&quot;

Winback: Customer has services which we have won from a competitor</inlineHelpText>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Winback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Score_INFOLEGALE__c.field-meta.xml
<CustomField>
    <fullName>Score_INFOLEGALE__c</fullName>
    <label>Score INFOLEGALE</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Digicel_Business_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Digicel Business Sales Process</businessProcess>
    <description>This record type is used to record all deals with Digicel Business customers</description>
    <label>Digicel Business Opportunity</label>
</RecordType>

DigicielFull/force-app/main/default/classes/InfolegaleOppBAT_TST.cls
/**
 * @description       : 
 * @author            : JBBARTHELEMY
 * @group             : 
 * @last modified on  : 08/11/2022
 * @last modified by  : JBBARTHELEMY
**/
@IsTest
public  class InfolegaleOppBAT_TST {
    
    @isTest
    static void testBatchInfolegale(){

        Map<String, Schema.RecordTypeInfo> accountRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id accClientRT = accountRTs.get('Digicel_Business_Account').getRecordTypeId();
        Map<String, Schema.RecordTypeInfo> oppRTs = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName();
        Id oppRTsId = oppRTs.get('Digicel_Business_Opportunity').getRecordTypeId();
        Account acc = new Account(
            Name = 'TEST',
            Active__c = true,
            BillingCity = 'Paris',
            TelesoftNumber__c = null,
            Registration_Number__c = '510464001',
            BillingCountryCode = 'BB',
            AvanceOrder__c = '',
            BillingPostalCode = '75004',
            BillingStreet = '7 rue de Rivoli',
            RecordTypeId = accClientRT);
        insert acc;
        Opportunity opp = new Opportunity(
            Name = 'Opportunity Test ',
            StageName = 'Commercial Review',
            Type = 'Standard Deal',
            SaleType__c = 'New',
            Country__c = 'Guadeloupe',
            Estimated_Billed_Date__c = Date.today().addDays(14),
            CurrencyIsoCode = 'USD',
            AccountId = acc.Id,
            RecordTypeId = oppRTsId,
            Product_Interest__c = 'Data VPN',
            CloseDate = Date.today().addDays(7)
        );
        insert opp;
       
        Test.setMock(HttpCalloutMock.class, new MockInfolegale_TST());
        Test.startTest();
        InfolegaleOpp_BAT httpBatch = new InfolegaleOpp_BAT(new Set<Id>{opp.Id});
        Id batchJobId = Database.executebatch(httpBatch,100);  
        Test.stopTest();

        Opportunity oppToTest = [SELECT Id, INFOLEGALERating__c, Score_INFOLEGALE__c, AccountId, StageName FROM Opportunity];
        system.assertEquals(6, oppToTest.INFOLEGALERating__c, 'oportunity rating infolegale score should be the same ');
        system.assertEquals(6, oppToTest.Score_INFOLEGALE__c, 'oportunity scoring infolegale score should be the same ');

        Account accToTest = [SELECT Id, INFOLEGALERating__c, Registration_Number__c FROM Account];
        system.assertEquals(6, accToTest.INFOLEGALERating__c, 'infolegale rating account should be the same');
    }

}