DigicielFull/force-app/main/default/objects/Account/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specialterms__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/TelesoftNumber__c.field-meta.xml
<CustomField>
    <fullName>TelesoftNumber__c</fullName>
    <label>N° DBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/ClientNumber__c.field-meta.xml
<CustomField>
    <fullName>ClientNumber__c</fullName>
    <label>Client ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceTelesoft_BAT_TST.cls
/**
 * @description       : 
 * @author            : JBBARTHELEMY
 * @group             : 
 * @last modified on  : 08/11/2022
 * @last modified by  : JBBARTHELEMY
**/
@isTest
public class InvoiceTelesoft_BAT_TST {
 
    @TestSetup
    static void makeData(){  
        Map<String, Schema.RecordTypeInfo> accountRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id accClientRT = accountRTs.get('Digicel_Business_Account').getRecordTypeId();
        Account acc = new Account(
            Name = 'TEST',
            Active__c = true,
            BillingCity = 'Paris',
            TelesoftNumber__c = '50092',
            Registration_Number__c = '510464001',
            BillingCountryCode = 'BB',
            AvanceOrder__c = '',
            BillingPostalCode = '75004',
            BillingStreet = '7 rue de Rivoli',
            RecordTypeId = accClientRT);
        insert acc;
       
        Test.setMock(HttpCalloutMock.class, new MockFactory_TST('MockInfolegale'));
        Test.startTest();
        Infolegale_BAT httpBatch = new Infolegale_BAT(new Set<Id>{acc.Id});
        Id batchJobId = Database.executebatch(httpBatch,100);   
        Test.stopTest();
    }

        @isTest
        static void testBatchClientTelesoft(){        
            Test.setMock(HttpCalloutMock.class, new MockFactory_TST('MockInvoiceTelesoft'));

            Test.startTest();
            InvoiceTelesoft_BAT httpBatch2 = new InvoiceTelesoft_BAT(0,1);
            Id batchJobId2 = Database.executebatch(httpBatch2,100);    
            Test.stopTest();
            
            Account acc = [SELECT Id, Name, TelesoftNumber__c , Registration_Number__c FROM Account];
            List<Invoice__c> listToCheck = [SELECT Id, Name, ClientNumber__c FROM Invoice__c WHERE ClientNumber__c = '50092' ];
            
            system.assert(listToCheck.size() > 0, 'size should be superior to 0');
        }

}