DigicielFull/force-app/main/default/objects/Account/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specialterms__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <formula>TEXT( Owner.Digicel_Country__c )</formula>
    <label>Digicel Country</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/TelesoftNumber__c.field-meta.xml
<CustomField>
    <fullName>TelesoftNumber__c</fullName>
    <label>N° DBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/ClientNumber__c.field-meta.xml
<CustomField>
    <fullName>ClientNumber__c</fullName>
    <label>Client ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/User/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <description>*****************************************DO NOT MODIFY THIS FIELD*****************************************

This field is used to report on users and what market they are assigned to. Workflow Rules, Approval Processes and other customization&apos;s rely on this field. Changing any of this field&apos;s attributes will cause adverse reactions in the system. 

*****************************************DO NOT MODIFY THIS FIELD*****************************************</description>
    <label>Digicel Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>BVI</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>FWI</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Saint Kitts and Nevis</fullName>
            </value>
            <value>
                <fullName>Saint Lucia</fullName>
            </value>
            <value>
                <fullName>Saint Vincent and the Grenadines</fullName>
            </value>
            <value>
                <fullName>Suriname</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>Turks and Caicos Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Tonga</fullName>
            </value>
            <value>
                <fullName>Vanuatu</fullName>
            </value>
            <value>
                <fullName>Group Business Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceKaldom_BAT_TST.cls
@isTest
public  class InvoiceKaldom_BAT_TST {


    @TestSetup
    static void makeData(){  
        Map<String, Schema.RecordTypeInfo> accountRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id accClientRT = accountRTs.get('Digicel_Business_Account').getRecordTypeId();

        User user = [SELECT Id FROM User WHERE Digicel_Country__c = 'FWI' LIMIT 1];

        Account acc = new Account(
            Name = 'TEST',
            Owner = user,
            Active__c = true,
            BillingCity = 'Paris',
            TelesoftNumber__c = '50092',
            Registration_Number__c = '510464001',
            BillingCountryCode = 'BB',
            AvanceOrder__c = '',
            BillingPostalCode = '75004',
            BillingStreet = '7 rue de Rivoli',
            RecordTypeId = accClientRT);
        AccountTriggerHandler.triggerDisabled = true;
        insert acc;
        AccountTriggerHandler.triggerDisabled = false;
    }

    @isTest
    static void testBatchInvoiceKaldom(){

        Test.setMock(HttpCalloutMock.class, new MockFactory_TST('MockLoginKaldom'));
        Test.setMock(HttpCalloutMock.class, new MockFactory_TST('MockInvoiceKaldom'));

        Test.startTest();
        Id batchJobId = Database.executebatch(new InvoiceKaldom_BAT(13,14), 100);   
        Test.stopTest();
        
        List<Invoice__c> listToCheck = [SELECT Id, Name, ClientNumber__c FROM Invoice__c WHERE ClientNumber__c = '2590'];
        System.assertEquals(2, listToCheck.size(), 'listToCheck should be equal to 2');

    }

}