DigicielFull/force-app/main/default/objects/Account/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specialterms__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>Account name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceID__c.field-meta.xml
<CustomField>
    <fullName>InvoiceID__c</fullName>
    <externalId>true</externalId>
    <label>Invoice ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TechMoreOlderThen12Months__c.field-meta.xml
<CustomField>
    <fullName>TechMoreOlderThen12Months__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TechMoreOlderThen12Months</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
                <default>true</default>
                <label>30 %</label>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {

    /** 
    * ********************************************************
    * This method is test data for create multiple Accounts
    * ********************************************************
    */
    public static List<Account> insertAccounts(Integer numRecords, Boolean doInsert) {
        Test.setMock(HttpCalloutMock.class, new MockFactory_TST('MockInfolegale'));
        List<Account> results = new List<Account>();
        Map<String, Schema.RecordTypeInfo> accountRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Map<String, Schema.RecordTypeInfo> oppRTs = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName();
        Id accClientRT = accountRTs.get('Digicel_Business_Account').getRecordTypeId();

        for (Integer counter = 1; counter <= numRecords; counter++) {
            Account record = new Account();
            record.Name = 'TEST'+counter;
            record.Active__c = true;
            record.BillingCity = 'Paris';
            record.BillingCountryCode = 'FR';
            record.AvanceOrder__c = '';
            record.Registration_Number__c = '00000';
            record.BillingPostalCode = '75004';
            record.BillingStreet = '7 rue de Rivoli';
            record.RecordTypeId = accClientRT;
            results.add(record);
        }
        if(doInsert){
            AccountTriggerHandler.triggerDisabled = true;
            insert results;
            AccountTriggerHandler.triggerDisabled = false;
        }
        return results;
    }

    /** 
    * ********************************************************
    * This method is test data for create one Account
    * ********************************************************
    */
    public static Account createAccount(Boolean doInsert) {
        Test.setMock(HttpCalloutMock.class, new MockFactory_TST('MockInfolegale'));
      
        Map<String, Schema.RecordTypeInfo> accountRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        // Map<String, Schema.RecordTypeInfo> oppRTs = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName();
        Id accClientRT = accountRTs.get('Digicel_Business_Account').getRecordTypeId();

        Account record = new Account();
        record.Name = 'TEST';
        record.Active__c = true;
        record.BillingCity = 'Paris';
        record.BillingCountryCode = 'FR';
        record.AvanceOrder__c = '';
        record.Registration_Number__c = '00000';
        record.BillingPostalCode = '75004';
        record.BillingStreet = '7 rue de Rivoli';
        record.RecordTypeId = accClientRT;
        if(doInsert){
            insert record;
        }
        return record;
    }

    /** 
    * ********************************************************
    * This method is test data for create multiple Invoices
    * ********************************************************
    */
    public static List<Invoice__c> insertInvoices(Integer numRecords, Account acc, Boolean doInsert) {
        List<Invoice__c> results = new List<Invoice__c>();
        for (Integer counter = 1; counter <= numRecords; counter++) {
            Invoice__c record = new Invoice__c();
            record.AccountName__c = acc.Id;
            record.InvoiceID__c = '111'+counter;
            record.TechMoreOlderThen12Months__c = true;
            results.add(record);
        }
        if(doInsert){
            insert results;
        }
        return results;
    }

}