DigicielFull/force-app/main/default/objects/Account/fields/AvanceOrder__c.field-meta.xml
<CustomField>
    <fullName>AvanceOrder__c</fullName>
    <label>% Avance à la commande</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specialterms__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 %</fullName>
            </value>
            <value>
                <fullName>30 %</fullName>
            </value>
            <value>
                <fullName>50 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/TelesoftNumber__c.field-meta.xml
<CustomField>
    <fullName>TelesoftNumber__c</fullName>
    <label>N° DBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

force-app/main/default/classes/ClientTelesoft_BAT_TST.cls
/**
 * @description       : 
 * @author            : JBBARTHELEMY
 * @group             : 
 * @last modified on  : 08/11/2022
 * @last modified by  : JBBARTHELEMY
**/
@isTest
public class ClientTelesoft_BAT_TST {
 
    @TestSetup
    static void makeData(){  
        Map<String, Schema.RecordTypeInfo> accountRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id accClientRT = accountRTs.get('Digicel_Business_Account').getRecordTypeId();
        Account acc = new Account(
            Name = 'TEST',
            Active__c = true,
            BillingCity = 'Paris',
            TelesoftNumber__c = null,
            Registration_Number__c = '510464001',
            BillingCountryCode = 'BB',
            AvanceOrder__c = '',
            BillingPostalCode = '75004',
            BillingStreet = '7 rue de Rivoli',
            RecordTypeId = accClientRT);
        insert acc;
        Test.setMock(HttpCalloutMock.class, new MockInfolegale_TST());
        Test.startTest();
        Infolegale_BAT httpBatch = new Infolegale_BAT(new Set<Id>{acc.Id});
        Id batchJobId = Database.executebatch(httpBatch,100);   
        Test.stopTest();
    }

        @isTest
        static void testBatchClientTelesoft(){
           
            Test.setMock(HttpCalloutMock.class, new MockClientTelesoft_TST());
            Test.startTest();
            ClientTelesoft_BAT httpBatch = new ClientTelesoft_BAT();
            Id batchJobId = Database.executebatch(httpBatch,100);    
            Test.stopTest();
            Account acc = [SELECT Id, Name, TelesoftNumber__c , Registration_Number__c FROM Account];
            system.assertEquals('50003', acc.TelesoftNumber__c, 'should be the same');
        }


}