DigicielFull/force-app/main/default/objects/Account/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Virgin Islands, British</fullName>
                <label>BVI</label>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>La Reunion</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Mayotte</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>St. Barthelemy</fullName>
            </value>
            <value>
                <fullName>St. Kitts and Nevis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <displayFormat>BL-{000000000}</displayFormat>
        <label>Backlog No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Backlog__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Backlogs</relationshipLabel>
    <relationshipName>Backlog</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Backlog__c/fields/Backlog_Currency__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Currency__c</fullName>
    <label>Backlog Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Backlog__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Month</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Select date of the Month</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>New Business Requirement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>zDeprecatedBacklog</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Digicel_Business_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Digicel Business Sales Process</businessProcess>
    <description>This record type is used to record all deals with Digicel Business customers</description>
    <label>Digicel Business Opportunity</label>
</RecordType>

DigicielFull/force-app/main/default/objects/Summary__c/Summary__c.object-meta.xml
<CustomObject>
    <label>Summary</label>
    <nameField>
        <displayFormat>{MM}-{YYYY}-{0000}</displayFormat>
        <label>Summary No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Summary__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Bosnia And Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/classes/testTriggerSummarizeBacklog.cls
@isTest(seeAllData=false)
private class testTriggerSummarizeBacklog{
    static testMethod void myUnitTest_BacklogSummary() {
        RecordType recordType_JamaicaOpp = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Opportunity' AND SobjectType = 'Opportunity'];
        RecordType recordType_JamaicaAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        RecordType recordType_HaitiAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        RecordType recordType_MarketAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        
        Account mktAcc = new Account(Name = 'Test Market Account',billing_Country__c='Jamaica', RecordTypeId = recordType_MarketAcc.Id);
        insert mktAcc;
        
        Account acc = new Account(Name = 'Test Account',billing_Country__c='Jamaica', RecordTypeId = recordType_JamaicaAcc.Id);
        insert acc;
        
        
        Test.startTest();
        
        Backlog__c backlog = new Backlog__c(Account_Name__c = mktAcc.Id, Date__c = System.today(), Target__c = 100, Backlog_Currency__c = 100, Current_Month__c = false);
        insert backlog;
        
        Backlog__c backlog2 = new Backlog__c(Account_Name__c = mktAcc.Id, Date__c = System.today().addMonths(1), Target__c = 100, Backlog_Currency__c = 100, Current_Month__c = true);
        insert backlog2;
        
        backlog.Target__c = 1000;
        update backlog;
        
        backlog.Date__c = System.today().addMonths(2);
        update backlog;
        
        delete backlog;
        
        acc.Billing_Country__c = 'Haiti';
        acc.RecordTypeId = recordType_HaitiAcc.Id;
        update acc;
        
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        String jobid = System.schedule('Prueba', CRON_EXP, new classVerifyBacklogsMonth());
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        // Verify the expressions are the same  
        System.assertEquals(CRON_EXP, ct.CronExpression);
    
        // Verify the job has not run  
        System.assertEquals(0, ct.TimesTriggered);
         
        Test.stopTest();
    }
    
    static testMethod void myUnitTest_BacklogWithoutSummary() {
        RecordType recordType_JamaicaOpp = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Opportunity' AND SobjectType = 'Opportunity'];
        RecordType recordType_JamaicaAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        RecordType recordType_HaitiAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        RecordType recordType_MarketAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        
        Account acc = new Account(Name = 'Test Market Account',billing_Country__c='Jamaica', RecordTypeId = recordType_MarketAcc.Id);
        insert acc;
        
        Test.startTest();
        Summary__c[] allSummary = [Select Id From Summary__c];
        for (Summary__c sm:allSummary) {
            delete sm;
        }
        
        Backlog__c backlog = new Backlog__c(Account_Name__c = acc.Id, Date__c = System.today(), Target__c = 100, Backlog_Currency__c = 100, Current_Month__c = false);
        insert backlog;
        
        allSummary = [Select Id From Summary__c];
        for (Summary__c sm:allSummary) {
            delete sm;
        }
        
        backlog.Date__c = System.today().addMonths(2);
        update backlog;
        
        allSummary = [Select Id From Summary__c];
        for (Summary__c sm:allSummary) {
            delete sm;
        }
        
        delete backlog;
         
        Test.stopTest();
    }
}