DigicielFull/force-app/main/default/objects/Account/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Virgin Islands, British</fullName>
                <label>BVI</label>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>La Reunion</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Mayotte</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>St. Barthelemy</fullName>
            </value>
            <value>
                <fullName>St. Kitts and Nevis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Digicel_Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Account</fullName>
    <active>true</active>
    <description>This record type is used to record all Digicel Business customers</description>
    <label>Digicel Business Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Actual_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Billed_Date__c</fullName>
    <label>Actual Billed Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>La Reunion</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Mayotte</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Nouvelle Caledonie</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Saint Barthelemy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Estimated_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Billed_Date__c</fullName>
    <label>Estimated Billed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Digicel_Business_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Business_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Digicel Business Sales Process</businessProcess>
    <description>This record type is used to record all deals with Digicel Business customers</description>
    <label>Digicel Business Opportunity</label>
</RecordType>

DigicielFull/force-app/main/default/objects/OpportunityLineItem/fields/Actual_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Billed_Date__c</fullName>
    <label>Actual Billed Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/OpportunityLineItem/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <inlineHelpText>MRC - Margin % field will default to 100%

Rental or Lease - Margin % field will default to 100%

OTC - Margin % field will default to 0%

Installation - Margin % field will default to 0%

PAYG - Margin % field will default to 0%</inlineHelpText>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
            <value>
                <fullName>NRR</fullName>
            </value>
            <value>
                <fullName>Rental or Lease</fullName>
            </value>
            <value>
                <fullName>PAYG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/OpportunityLineItem/fields/Margin_markup_percent__c.field-meta.xml
<CustomField>
    <fullName>Margin_markup_percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Margin%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Net_Value_AOP_MRC__c.field-meta.xml
<CustomField>
    <fullName>Net_Value_AOP_MRC__c</fullName>
    <formula>AOP_MRC__c * Margin_markup_percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Value AOP MRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/OpportunityLineItem/fields/Net_Value_AOP_MRC_Currency__c.field-meta.xml
<CustomField>
    <fullName>Net_Value_AOP_MRC_Currency__c</fullName>
    <label>Net Value AOP MRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <businessOwnerGroup>SFDC_Admin_Team</businessOwnerGroup>
    <description>this field was originally intended to handle the MRC &amp; OTC charge types by making this a static refernce on the product. Digicel instead opted for the opportunity line item level &quot;charge type&quot; field.

This field is being depracated as there have been issues with duplicate fields in reports</description>
    <label>zDEPRACATED Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
            <value>
                <fullName>Rental or Lease</fullName>
            </value>
            <value>
                <fullName>PAYG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>FWI</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>St. Kitts And Nevis</fullName>
            </value>
            <value>
                <fullName>St. Lucia</fullName>
            </value>
            <value>
                <fullName>St. Vincent</fullName>
            </value>
            <value>
                <fullName>Suriname</fullName>
            </value>
            <value>
                <fullName>Trinidad &amp; Tobago</fullName>
            </value>
            <value>
                <fullName>Turks &amp; Caicos Islands</fullName>
            </value>
            <value>
                <fullName>Virgin Islands, British</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/classes/testTriggerOpportunityAOP.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest (seeAllData=true)
public class testTriggerOpportunityAOP {
    static testMethod void myTest_OpportunityAOP() {
        
        RecordType recordType_JamaicaOpp = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Opportunity' AND SobjectType = 'Opportunity'];
        RecordType recordType_JamaicaAcc = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Business_Account' AND SobjectType = 'Account'];
        
        Account acc = new Account(RecordTypeId = recordType_JamaicaAcc.Id, Name = 'Test Account', billing_Country__c='Jamaica' );
        insert acc;
        
        
        Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
        
        Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1', isActive=true);
        insert pbk1;
        
        Product2 prd = new Product2 (Name='Test Product 1', Country__c='Jamaica', Description='Test Product Entry 1',productCode = '321', isActive = true);
        insert prd;
        
        
        PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd.id,Pricebook2ID=standardPb.id,UnitPrice=40, isActive=true);
        insert pbe1;
        
            //Opportunity[] oppsToCreate = new Opportunity[]{};

        //for(Integer x=0; x<3;x++){
        Opportunity opp1 = new Opportunity (Name='JM-TestOpp',StageName='none', Estimated_Billed_Date__c=Date.today()+20,CloseDate=Date.today()+10,Pricebook2Id = pbe1.Pricebook2Id, AccountId = acc.id, RecordTypeId = recordType_JamaicaOpp.Id, Country__c = 'Jamaica');

            
        insert opp1;
            
       
            
        //insert oppsToCreate;
        
    
     //Opportunity[] oppsadded = [SELECT Id FROM Opportunity WHERE Id IN : oppsToCreate];        
     //for (Opportunity opp2 : oppsadded){
        OpportunityLineItem lineItem1 = new OpportunityLineItem (OpportunityID=opp1.Id,PriceBookEntryID=pbe1.id, quantity=4, Margin_markup_percent__c = 40, Charge_Type__c='Installation');
        insert lineItem1;
        OpportunityLineItem lineItem2 = new OpportunityLineItem (OpportunityID=opp1.Id,PriceBookEntryID=pbe1.id, Margin_markup_percent__c = 40, quantity=4,Charge_Type__c='OTC');
        insert lineItem2;
        OpportunityLineItem lineItem3 = new OpportunityLineItem (OpportunityID=opp1.Id,PriceBookEntryID=pbe1.id, Margin_markup_percent__c = 40, quantity=4,Charge_Type__c='MRC');
        insert lineItem3;


              
        
        //}
                

        Test.startTest();
        
   
                
        opp1.CloseDate = System.today().addMonths(2);
        //opp1.Actual_Billed_Date__c = System.today().addMonths(3);
        
        opp1.Estimated_Billed_Date__c = System.today().addMonths(3);
        update opp1;
        
        System.assertEquals(lineItem3.Net_Value_AOP_MRC__c, lineItem3.Net_Value_AOP_MRC_Currency__c);                
        
        
        
        
        
       
        
   
        
        Test.stopTest();
    
    }

}