DigicielFull/force-app/main/default/objects/Account/fields/Deposits_Waived__c.field-meta.xml
<CustomField>
    <fullName>Deposits_Waived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deposits Waived?</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>La Reunion</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Mayotte</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Nouvelle Caledonie</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Saint Barthelemy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Go_Live_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Go Live Date Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>FWI</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>St. Kitts And Nevis</fullName>
            </value>
            <value>
                <fullName>St. Lucia</fullName>
            </value>
            <value>
                <fullName>St. Vincent</fullName>
            </value>
            <value>
                <fullName>Suriname</fullName>
            </value>
            <value>
                <fullName>Trinidad &amp; Tobago</fullName>
            </value>
            <value>
                <fullName>Turks &amp; Caicos Islands</fullName>
            </value>
            <value>
                <fullName>Virgin Islands, British</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Product2/fields/Monthly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Fee__c</fullName>
    <label>Monthly Fee</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Product2/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityUpdate_TestClass.cls
@isTest(seeAllData=true)
private class OpportunityUpdate_TestClass{

    public static testMethod void test_setOpportunityTotals(){
    
        //Set up some variables
        //Create Account
        Account AccountObject = new Account();
        AccountObject.Name = 'Test';
        AccountObject.Deposits_Waived__c = true;
        insert AccountObject;
        
        //Create Opportunity
        Opportunity OpportunityObject = new Opportunity();
        OpportunityObject.Name = 'Test';
        OpportunityObject.StageName = 'Prospecting';
        OpportunityObject.CloseDate = system.today().addDays(10);
        OpportunityObject.AccountId = AccountObject.Id;
        OpportunityObject.Country__c = 'Jamaica';
        OpportunityObject.Go_Live_Date__c = date.today();
        OpportunityObject.Go_Live_Date_Approved__c = TRUE;
        insert OpportunityObject;
        
        
        Pricebook2 pbook = [select id from Pricebook2 where IsStandard = true limit 1];
        
        //Create Product 
        Product2 ProductObject = new Product2();
        ProductObject.Family = 'Test Product Family';
        ProductObject.Name = 'Test Product';
        ProductObject.Country__c = 'Jamaica';
        ProductObject.IsActive = TRUE;
        ProductObject.Security_Deposit__c = 10;
        ProductObject.Monthly_Fee__c = 10;
        insert ProductObject;
        
        //Create Aditional PricebookEntry
        PricebookEntry PricebookEntryObject = new PricebookEntry();
        PricebookEntryObject.Pricebook2Id = pbook.Id;
        PricebookEntryObject.Product2Id = ProductObject.Id;
        PricebookEntryObject.UnitPrice = 0.0;
        PricebookEntryObject.isActive = TRUE;
        insert PricebookEntryObject;
        
        Test.startTest();
        
        //1- Test add a new opportunity line item with deposit waived
        OpportunityLineItem OpportunityLineItemObject = new OpportunityLineItem();
        OpportunityLineItemObject.OpportunityId = OpportunityObject.Id;
        OpportunityLineItemObject.PricebookEntryId = PricebookEntryObject.Id;
        OpportunityLineItemObject.Quantity = 1;
        OpportunityLineItemObject.TotalPrice = 0.0;
        insert OpportunityLineItemObject;
        
        OpportunityLineItem[] oppLineItems = new OpportunityLineItem[]{OpportunityLineItemObject};
        
        OpportunityUpdate.setOpportunityTotals(oppLineItems);
        
        //2- test delete the opportunity line item with deposit waived 
        delete OpportunityLineItemObject;
        
        //3- test add a new opportunity line item without deposit waived
        AccountObject.Deposits_Waived__c = FALSE;
        upsert AccountObject;
        
        OpportunityLineItem OpportunityLineItemObject2 = new OpportunityLineItem();
        OpportunityLineItemObject2.OpportunityId = OpportunityObject.Id;
        OpportunityLineItemObject2.PricebookEntryId = PricebookEntryObject.Id;
        OpportunityLineItemObject2.Quantity = 1;
        OpportunityLineItemObject2.TotalPrice = 0.0;
        insert OpportunityLineItemObject2;
        
        oppLineItems = new OpportunityLineItem[]
        {OpportunityLineItemObject2};            
        
        OpportunityUpdate.setOpportunityTotals(oppLineItems);
        
        Test.stopTest();
        
    }
}