DigicielFull/force-app/main/default/objects/Account/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <formula>TEXT( Owner.Digicel_Country__c )</formula>
    <label>Digicel Country</label>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/TelesoftNumber__c.field-meta.xml
<CustomField>
    <fullName>TelesoftNumber__c</fullName>
    <label>N° DBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>Account name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Without taxes</inlineHelpText>
    <label>HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/AmountTTC__c.field-meta.xml
<CustomField>
    <fullName>AmountTTC__c</fullName>
    <inlineHelpText>Including tax</inlineHelpText>
    <label>TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/ClientNumber__c.field-meta.xml
<CustomField>
    <fullName>ClientNumber__c</fullName>
    <label>Client ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceID__c.field-meta.xml
<CustomField>
    <fullName>InvoiceID__c</fullName>
    <externalId>true</externalId>
    <label>Invoice ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Kaldom</fullName>
            </value>
            <value>
                <fullName>SeV</fullName>
            </value>
            <value>
                <fullName>Telesoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TechMoreOlderThen12Months__c.field-meta.xml
<CustomField>
    <fullName>TechMoreOlderThen12Months__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TechMoreOlderThen12Months</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Invoice__c/fields/TVA__c.field-meta.xml
<CustomField>
    <fullName>TVA__c</fullName>
    <label>TVA</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/classes/InvoiceTelesoft_BAT.cls
/**
 * @description       : 
 * @author            : JBBARTHELEMY
 * @group             : 
 * @last modified on  : 08/11/2022
 * @last modified by  : JBBARTHELEMY
**/
global class InvoiceTelesoft_BAT implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.stateful {

    public Integer firstNumber;
    public Integer secondNumber;
    private List<FactureTelesoftWrapper> repBody;
    private Map<String, List<FactureTelesoftWrapper>> mapTelesoftNumberFac = new Map<String, List<FactureTelesoftWrapper>>();

    public InvoiceTelesoft_BAT(Integer firstParam, Integer secondParam) {
        firstNumber = firstParam;
        secondNumber = secondParam;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime todaysDate = System.today().addMonths(-firstNumber);
        DateTime lastMonthDate = System.today().addMonths(-secondNumber);
        String todaysDateStr = todaysDate.format('yyyy-MM-dd');
        String lstMonthDateStr = lastMonthDate.format('yyyy-MM-dd');

        HttpResponse resFacture = new HttpResponse();
        resFacture = TelesoftWebService.apiReturnFacturesByDate(lstMonthDateStr,todaysDateStr);
        repBody = FactureTelesoftWrapper.parse(resFacture.getBody());
        List<String> lstTelesoftNumber = new List<String>();
        for(FactureTelesoftWrapper fac : repBody){
            if(!mapTelesoftNumberFac.containsKey(fac.Compte_client)){
                mapTelesoftNumberFac.put(fac.Compte_client, new List<FactureTelesoftWrapper>());
            }
            mapTelesoftNumberFac.get(fac.Compte_client).add(fac); 
        }
        for(String numeroClients : mapTelesoftNumberFac.keySet() ){
            lstTelesoftNumber.add('%' + numeroClients +'%');
        }
        return Database.getQueryLocator([SELECT Id, Name, TelesoftNumber__c, Registration_Number__c FROM Account WHERE TelesoftNumber__c LIKE :lstTelesoftNumber AND Owner.Digicel_Country__c = 'FWI']);            
    }

    global void execute(Database.BatchableContext bc, List<Account> accountsTelesoft){

            List<Invoice__c> lstInvoiceToUpsert = new List<Invoice__c>();

            for(Account acc : accountsTelesoft){
             
                List<String> telesoftIds = new List<String>();
                if(acc.TelesoftNumber__c.contains(';')){
                    telesoftIds = acc.TelesoftNumber__c.split(';');
                }  else {
                    telesoftIds.add(acc.TelesoftNumber__c);
                }
                for(String telesoftId : telesoftIds){
                    if(mapTelesoftNumberFac.get(telesoftId) != null){
                        for(FactureTelesoftWrapper fac : mapTelesoftNumberFac.get(telesoftId)){  
                   
                            if(telesoftId == fac.Compte_client){
                                Invoice__c inv = new Invoice__c();
                                //inv.InvoiceDate__c = Date.parse(fac.Date_facture);11/02/2023
                                if(fac.Date_facture != null ){
                                    string[] RFQdate = String.valueOf(fac.Date_facture.trim()).split('/');
                                    inv.InvoiceDate__c = date.valueOf(RFQdate[2] + '-' + RFQdate[1] + '-' + RFQdate[0]);
                                }
                                inv.ClientNumber__c = fac.Compte_client;
                                inv.AccountName__c = acc.Id;   
                                inv.Invoice_Number__c = fac.Id_facture;
                                inv.InvoiceID__c = fac.Id_facture + '/' + fac.Id_produit + '/' + acc.Id;
                                inv.Amount__c = Double.valueOf((fac.Prix_HT).replaceAll(',', '.').replaceAll(' ', ''));
                                inv.Source__c = 'Telesoft';
                                inv.AmountTTC__c = InvoiceTelesoft_SVE.calculAmountTTC(fac.Prix_HT, fac.Taux_TVA);
                                inv.TVA__c = InvoiceTelesoft_SVE.calculAmountTVA(fac.Prix_HT, fac.Taux_TVA);
                                inv.CurrencyIsoCode = 'EUR';
    
                                if(inv.InvoiceDate__c > Date.today().addYears(-1)){
                                    inv.TechMoreOlderThen12Months__c = true;
                                } else {
                                    inv.TechMoreOlderThen12Months__c = false;
                                }
                                lstInvoiceToUpsert.add(inv);
                            }
                        }
                    }
                }
            }

            Map<String, Map<String, Invoice__c>> mapInvoiceToInsert = new Map<String, Map<String, Invoice__c>>();
            if(lstInvoiceToUpsert.size() > 0) {
                for(Invoice__c inv : lstInvoiceToUpsert){

                    if (!mapInvoiceToInsert.containsKey(inv.AccountName__c)) {
                        mapInvoiceToInsert.put(inv.AccountName__c, new Map<String, Invoice__c>());
                    }

                    if(mapInvoiceToInsert.get(inv.AccountName__c).get(inv.Invoice_Number__c) == null){
                        mapInvoiceToInsert.get(inv.AccountName__c).put(inv.Invoice_Number__c, inv);
                    } else {
                        mapInvoiceToInsert.get(inv.AccountName__c).get(inv.Invoice_Number__c).Amount__c += inv.Amount__c ;
                        mapInvoiceToInsert.get(inv.AccountName__c).get(inv.Invoice_Number__c).TVA__c += inv.TVA__c ;
                        mapInvoiceToInsert.get(inv.AccountName__c).get(inv.Invoice_Number__c).AmountTTC__c += inv.AmountTTC__c ;              
                    }
                }
            }


            List<Invoice__c> lstInvoice = new List<Invoice__c>();
            if(mapInvoiceToInsert != null && mapInvoiceToInsert.size() > 0) {
                for(String idAccount : mapInvoiceToInsert.keySet() ){
                    for(String invId : mapInvoiceToInsert.get(idAccount).keyset()) {
                        lstInvoice.add(mapInvoiceToInsert.get(idAccount).get(invId));
                    }
                }
              
            }
        
            if(lstInvoice.size() > 0){
                try {
                    database.upsert(lstInvoice, Invoice__c.InvoiceID__c);
                } catch(DmlException e) {
                    System.debug('Exception sur l\'upsert des factures: ' + e.getMessage());
                }  
            }     
    }

    global void finish(Database.BatchableContext bc){  
        if(firstNumber < 13){
            firstNumber += 1;
            secondNumber += 1;
            Id batchJobId = Database.executebatch( new InvoiceTelesoft_BAT(firstNumber,secondNumber), 100);
        }
        system.debug('Traitement Batch terminé');
    }    

}