DigicielFull/force-app/main/default/objects/Account/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <formula>TEXT( Owner.Digicel_Country__c )</formula>
    <label>Digicel Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <label>Sales Representative</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/recordTypes/Digicel_PNG.recordType-meta.xml
<RecordType>
    <fullName>Digicel_PNG</fullName>
    <active>true</active>
    <label>Digicel PNG</label>
</RecordType>

DigicielFull/force-app/main/default/objects/Account/recordTypes/Digicel_Trends.recordType-meta.xml
<RecordType>
    <fullName>Digicel_Trends</fullName>
    <active>true</active>
    <label>Trend Global</label>
</RecordType>

force-app/main/default/objects/Commission_Target__c/Commission_Target__c.object-meta.xml
<CustomObject>
    <label>Commission / Target</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions / Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Target__c/fields/Commission_Rate_per_Activation__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate_per_Activation__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commission Rate per Activation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission_Target__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Commission_Target__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Digicel PNG, Digicel PNG Data Nets, Digicel PNG NEC, Digicel Nauru, Digicel Fiji, Digicel Vanuatu, Digicel Samoa, Digicel Tonga, Digicel PNG Remington</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Commissions / Targets</relationshipLabel>
    <relationshipName>Commissions_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Commission_Target__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Digicel_Country__c</field>
            <operation>equals</operation>
            <value>Fiji, PNG, Samoa, Vanuatu, Tonga, Nauru</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Commissions_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua And Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>La Reunion</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Mayotte</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Nouvelle Caledonie</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Saint Barthelemy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <formula>TEXT(  Owner.Digicel_Country__c  )</formula>
    <label>Digicel Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Go_Live_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Go Live Date Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <businessOwnerGroup>SFDC_Admin_Team</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>functionality is no longer required</description>
    <label>zDeprecated - Monthly Target</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Monthly_ICT_GSM_Targets__c.ICT_User_Target_Records__r.ICT_Sales_Represenative__c</field>
            <operation>equals</operation>
            <valueField>$Source.OwnerId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Monthly_ICT_GSM_Targets__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>French Guiana</fullName>
            </value>
            <value>
                <fullName>FWI</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guadeloupe</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Martinique</fullName>
            </value>
            <value>
                <fullName>Montserrat</fullName>
            </value>
            <value>
                <fullName>Nevis</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>St. Kitts And Nevis</fullName>
            </value>
            <value>
                <fullName>St. Lucia</fullName>
            </value>
            <value>
                <fullName>St. Vincent</fullName>
            </value>
            <value>
                <fullName>Suriname</fullName>
            </value>
            <value>
                <fullName>Trinidad &amp; Tobago</fullName>
            </value>
            <value>
                <fullName>Turks &amp; Caicos Islands</fullName>
            </value>
            <value>
                <fullName>Virgin Islands, British</fullName>
            </value>
            <value>
                <fullName>Papua New Guinea</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Product2/fields/Monthly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Fee__c</fullName>
    <label>Monthly Fee</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Product2/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Digicel_PNG.recordType-meta.xml
<RecordType>
    <fullName>Digicel_PNG</fullName>
    <active>true</active>
    <description>Digicel PNG Products</description>
    <label>Digicel PNG</label>
</RecordType>

DigicielFull/force-app/main/default/objects/User/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <description>*****************************************DO NOT MODIFY THIS FIELD*****************************************

This field is used to report on users and what market they are assigned to. Workflow Rules, Approval Processes and other customization&apos;s rely on this field. Changing any of this field&apos;s attributes will cause adverse reactions in the system. 

*****************************************DO NOT MODIFY THIS FIELD*****************************************</description>
    <label>Digicel Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>BVI</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Curacao</fullName>
            </value>
            <value>
                <fullName>Dominica</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>FWI</fullName>
            </value>
            <value>
                <fullName>Grenada</fullName>
            </value>
            <value>
                <fullName>Guyana</fullName>
            </value>
            <value>
                <fullName>Haiti</fullName>
            </value>
            <value>
                <fullName>Jamaica</fullName>
            </value>
            <value>
                <fullName>Panama</fullName>
            </value>
            <value>
                <fullName>Saint Kitts and Nevis</fullName>
            </value>
            <value>
                <fullName>Saint Lucia</fullName>
            </value>
            <value>
                <fullName>Saint Vincent and the Grenadines</fullName>
            </value>
            <value>
                <fullName>Suriname</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>Turks and Caicos Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Tonga</fullName>
            </value>
            <value>
                <fullName>Vanuatu</fullName>
            </value>
            <value>
                <fullName>Group Business Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityLineItemUpdate_TestClass.cls
@isTest(seeAllData=true)
private class OpportunityLineItemUpdate_TestClass{

    public static testMethod void test_setFields(){
        //Create Account
        Id rtId_trend = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_Trends' And SObjectType = 'Account'].Id;
        Account AccountObject = new Account(Name= 'Test', RecordTypeId = rtId_trend);
        insert AccountObject;
    
        //Create Opportunity
        Opportunity OpportunityObject = new Opportunity();
        OpportunityObject.Name = 'Test';
        OpportunityObject.StageName = 'Prospecting';
        OpportunityObject.CloseDate = system.today().addDays(10);
        OpportunityObject.AccountId = AccountObject.Id;
        OpportunityObject.OwnerId = userinfo.getUserId();
        OpportunityObject.Go_Live_Date__c = date.today();
        OpportunityObject.Go_Live_Date_Approved__c = TRUE;
        insert OpportunityObject;
        
        Pricebook2 pbook = [select id from Pricebook2 where IsStandard = true limit 1];
        
        Id rtId_PNG = [SELECT Id FROM RecordType WHERE DeveloperName = 'Digicel_PNG' And SObjectType = 'Product2'].Id;
        
        User usuario = new User(Id = userinfo.getUserId(), Digicel_Country__c = 'PNG');
        update usuario;
        
        //Create Product
        Product2 ProductObject = new Product2();
        ProductObject.Family = 'Test Product Family';
        ProductObject.Name = 'Test Product';
        ProductObject.Country__c = 'Jamaica';
        ProductObject.isActive = TRUE;
        ProductObject.Security_Deposit__c = 10;
        ProductObject.Monthly_Fee__c = 10;
        ProductObject.RecordTypeId = rtId_PNG;
        insert ProductObject;
        
        //Create Commission and Target
        Commission_Target__c oneCT = new Commission_Target__c();
        oneCT.Sales_Representative__c = usuario.Id;
        oneCT.Monthly_Target__c = 100;
        oneCT.Commission_Rate_per_Activation__c = 100;
        oneCT.Product__c = ProductObject.Id;
        insert oneCT;
        
        //Create Aditional PricebookEntry
        PricebookEntry PricebookEntryObject = new PricebookEntry();
        PricebookEntryObject.Pricebook2Id = pbook.Id;
        PricebookEntryObject.Product2Id = ProductObject.Id;
        PricebookEntryObject.UnitPrice = 0.0;
        PricebookEntryObject.isActive = TRUE;
        insert PricebookEntryObject;
        
        //Create OpportunityLineItem 
        OpportunityLineItem oppli = new OpportunityLineItem();
        oppli.OpportunityId = OpportunityObject.Id;
        oppli.PricebookEntryId = PricebookEntryObject.Id;
        oppli.Quantity = 1;
        oppli.TotalPrice = 0.0;
        insert oppli;
        
        OpportunityLineItem[] opls = new OpportunityLineItem[]{oppli};
        
        Test.startTest();
        
        OpportunityLineItemUpdate.setFields(opls);
        
        Test.stopTest();
        
    }
  
}