DigicielFull/force-app/main/default/objects/Account/fields/Digicel_Country__c.field-meta.xml
<CustomField>
    <fullName>Digicel_Country__c</fullName>
    <formula>TEXT( Owner.Digicel_Country__c )</formula>
    <label>Digicel Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/INFOLEGALERating__c.field-meta.xml
<CustomField>
    <fullName>INFOLEGALERating__c</fullName>
    <label>Infolegale Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration #</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DigicielFull/force-app/main/default/classes/Infolegale_BAT.cls
/**
 * @description       : 
 * @author            : JBBARTHELEMY
 * @group             : 
 * @last modified on  : 08/11/2022
 * @last modified by  : JBBARTHELEMY
**/
global class Infolegale_BAT implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.stateful {

    private Set<Id> setIdAccount;

    public Infolegale_BAT(Set<Id> strParam) {
        setIdAccount = strParam;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {  
        // return Database.getQueryLocator([SELECT Id, INFOLEGALERating__c, Registration_Number__c FROM Account WHERE Id IN :setIdAccount]);            
        return Database.getQueryLocator([SELECT Id, INFOLEGALERating__c, Registration_Number__c FROM Account WHERE Id IN :setIdAccount AND Owner.Digicel_Country__c = 'FWI']);            
    }

    global void execute(Database.BatchableContext bc, List<Account> accountsToUpdate){
        for(Account account : accountsToUpdate){
            String siren = account.Registration_Number__c;
            HttpResponse resScore = new HttpResponse();
            resScore = InfolegaleWebService.getDataInfolegale(siren);
            Integer code = resScore.getStatusCode();
            Integer score;
            if(code == 200){
                InfolegaleWrapper repBody = InfolegaleWrapper.parse(resScore.getBody());               
                score = repBody.score;
            } else {
                score = null;
            }
            account.INFOLEGALERating__c = score;
        }
        AccountTriggerHandler.triggerDisabled = true;
        database.update(accountsToUpdate);     
        AccountTriggerHandler.triggerDisabled = false;
    }

    global void finish(Database.BatchableContext bc){}    

}