DigicielFull/force-app/main/default/objects/Account/fields/PNG_EntitlementLevel__c.field-meta.xml
<CustomField>
    <fullName>PNG_EntitlementLevel__c</fullName>
    <label>Entitlement Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PNG_CaseType__c.field-meta.xml
<CustomField>
    <fullName>PNG_CaseType__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>ICT &amp; GSM</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/objects/Case/fields/PNG_RootCause__c.field-meta.xml
<CustomField>
    <fullName>PNG_RootCause__c</fullName>
    <label>Root Cause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fibre Damage</fullName>
            </value>
            <value>
                <fullName>LAN issue</fullName>
            </value>
            <value>
                <fullName>Line of Sight</fullName>
            </value>
            <value>
                <fullName>03B Outage</fullName>
            </value>
            <value>
                <fullName>PMP Node Offline</fullName>
            </value>
            <value>
                <fullName>SM Idle</fullName>
            </value>
            <value>
                <fullName>Power Issue – site</fullName>
            </value>
            <value>
                <fullName>Power Issue – customer</fullName>
            </value>
            <value>
                <fullName>IP core issue</fullName>
            </value>
            <value>
                <fullName>International link issue</fullName>
            </value>
            <value>
                <fullName>Transmission issue</fullName>
            </value>
            <value>
                <fullName>RF Interference</fullName>
            </value>
            <value>
                <fullName>Capacity exceeded</fullName>
            </value>
            <value>
                <fullName>Faulty equipment – customer</fullName>
            </value>
            <value>
                <fullName>Faulty play box-no power</fullName>
            </value>
            <value>
                <fullName>Faulty connectors/splitters-loose/broken</fullName>
            </value>
            <value>
                <fullName>Faulty cable-cut/worn out</fullName>
            </value>
            <value>
                <fullName>Broken/Damaged Antenna or Dish</fullName>
            </value>
            <value>
                <fullName>Faulty parts &gt; example: LNB/Amplifier/etc…</fullName>
            </value>
            <value>
                <fullName>Relocation/Move</fullName>
            </value>
            <value>
                <fullName>Relocate of antenna/dish</fullName>
            </value>
            <value>
                <fullName>Removal of equipment(antenna/dish/cable)</fullName>
            </value>
            <value>
                <fullName>New Hook up(s)</fullName>
            </value>
            <value>
                <fullName>Additional Installation(s)</fullName>
            </value>
            <value>
                <fullName>Swap from DTT to DTH</fullName>
            </value>
            <value>
                <fullName>Extension of cable(s)</fullName>
            </value>
            <value>
                <fullName>Termination &amp; Commissioning</fullName>
            </value>
            <value>
                <fullName>No signal</fullName>
            </value>
            <value>
                <fullName>Scramble message</fullName>
            </value>
            <value>
                <fullName>Pixelate pictures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entitlement/fields/PNG_EntitlementType__c.field-meta.xml
<CustomField>
    <fullName>PNG_EntitlementType__c</fullName>
    <label>Entitlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Services</fullName>
            </value>
            <value>
                <fullName>Connectivity &amp; Enterprise Services</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DigicielFull/force-app/main/default/classes/PNG_CaseTriggerHelper.cls
public without sharing class PNG_CaseTriggerHelper {
    /**
     * This method will search for all level one child cases for the
     * current parent and mark the status closed and also update the Root Cause
     */
    public static void closeAllLevelOneChildCases(List<Case> newCases, Map<Id, Case> oldCases){
        Boolean stopTrigger = Boolean.valueOf(Label.PNG_StopCaseManagementTrigger);        
        try{
            if(!stopTrigger){
                List<Case> childCasesToUpdate = new List<Case>();        
                Set<Id> setParentClosedCases = getAllClosedCasesInCurrentContext(newCases, oldCases);
                
                if(!setParentClosedCases.isEmpty()){
                    for(Case childCase : [SELECT Id, Status, Parent.Id, Parent.Status, Parent.PNG_RootCause__c FROM Case WHERE Parent.Id IN :setParentClosedCases]){
                        childCase.Status = childCase.Parent.status;
                        childCase.PNG_RootCause__c = childCase.Parent.PNG_RootCause__c;
                        childCasesToUpdate.add(childCase);
                    }
                }
                if(childCasesToUpdate.size()>0){
                    update childCasesToUpdate;
                }
            }
        }catch(Exception ex){
            System.debug('DildarLog: Exception @closeAllLevelOneChildCases - '+ex.getMessage());
        }
    }
    
    private static Set<Id> getAllClosedCasesInCurrentContext(List<Case> newCases, Map<Id, Case> oldCases){
        Set<Id> setProcessedParentClosedCases = new Set<Id>();
        for(Case parentCaseRec:newCases) {
                if(parentCaseRec.status != oldCases.get(parentCaseRec.id).status &&
                   parentCaseRec.IsClosed &&
                   parentCaseRec.RecordTypeId == Label.PNG_CaseSupportRecordType){
                   
                       setProcessedParentClosedCases.add(parentCaseRec.Id);
			}
		}
        return setProcessedParentClosedCases;
    }
    public static void selectEntitlementForSupportCase(List<Case> newCases){
        
        List<Case> casesToUpdate =  new List<Case>();
        Set<id> accountsOfCases = new Set<id>();
        for(Case c : newCases){
            if(c.AccountId != null){
            	accountsOfCases.add(c.AccountId);
            }
        }
        Map<Id, Account> accountsWithEntitlements = new Map<Id, Account>([Select id, PNG_EntitlementLevel__c,
                                                                    (select id, StartDate, EndDate, PNG_EntitlementType__c from Entitlements Where Status='Active' 
                                                                     Order By createdDate desc)
                                                                    from Account where Id IN: accountsOfCases]);
        
        for(Case cas : newCases){
            if(cas.AccountId != null && accountsWithEntitlements != null && accountsWithEntitlements.containsKey(cas.AccountId)){
                Account acc = accountsWithEntitlements.get(cas.AccountId);
                if(acc.Entitlements != null && acc.Entitlements.size()>0){
                    cas.EntitlementId = null;
                    for(Entitlement ent : acc.Entitlements){
                       if((cas.PNG_CaseType__c == 'ICT' || cas.PNG_CaseType__c == 'ICT & GSM') && ent.PNG_EntitlementType__c =='Connectivity & Enterprise Services'){
                            cas.EntitlementId = ent.id;
                        }else if(cas.PNG_CaseType__c == 'GSM' && ent.PNG_EntitlementType__c =='Mobile Services'){
                            cas.EntitlementId = ent.id;
                        }
                        casesToUpdate.add(cas);
                    }
                }
            }
        }
        
    }
}