force-app/main/default/objects/Opportunity/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Go_Live_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Go Live Date Approved</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Pre_Sales_Request__c/Pre_Sales_Request__c.object-meta.xml
<CustomObject>
    <description>Pre Sales request</description>
    <label>Pre Sales Request</label>
    <nameField>
        <displayFormat>PSR-{000000000}</displayFormat>
        <label>Pre Sales Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Sales Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Pre_Sales_Request__c/recordTypes/Pre_Sales_Request.recordType-meta.xml
<RecordType>
    <fullName>Pre_Sales_Request</fullName>
    <active>true</active>
    <label>Pre Sales Request</label>
</RecordType>

DigicielFull/force-app/main/default/classes/PreSalesRequestController_TestClass.cls
@isTest(seeAllData= true)
public class PreSalesRequestController_TestClass{

    public static testmethod void PreSalesRequestController_Positivetest()
    {
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Pre_Sales_Request__c' LIMIT 1];
        
        //Create new Pre_Sales_Request
        Pre_Sales_Request__c testPSR = new Pre_Sales_Request__c();
        testPSR.RecordTypeId = rt.Id;
        
        //Create new Opportunity
        Opportunity opp = new Opportunity();
        opp.Name = 'JM-Abc';
        opp.StageName = 'Proposal';
        Date tomorrow = date.today();
        tomorrow.addDays(1);
        opp.CloseDate = tomorrow;
        opp.Go_Live_Date__c = date.today();
        opp.Go_Live_Date_Approved__c = TRUE;
        insert opp;
        
        Test.StartTest();
        PageReference pagetest = new PageReference('/apex/PreSalesRequestCreation');
        pagetest.getParameters().put('currentPageURL','https://example.com/apex/PreSalesRequestCreation?retUrl=/'+opp.Id+'%3Fisdtp%3Dmn');
        Test.setCurrentPageReference(pagetest); 
        
        //Create an instance of the controller 
        redirectPreSalesRequestController testController = new redirectPreSalesRequestController(
        new ApexPages.StandardController(testPSR));
        
        //Calling method
        testController.getOpportunityLandingPage();
        testController.redirectPreSalesRequest();
        
        Test.StopTest();
    }
}