force-app/main/default/objects/Opportunity/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Go_Live_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Go Live Date Approved</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Pre_Sales_Request__c/Pre_Sales_Request__c.object-meta.xml
<CustomObject>
    <description>Pre Sales request</description>
    <label>Pre Sales Request</label>
    <nameField>
        <displayFormat>PSR-{000000000}</displayFormat>
        <label>Pre Sales Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Sales Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Pre_Sales_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pre Sales Requests</relationshipLabel>
    <relationshipName>ICT_Customer_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Pre_Sales_Update__c/Pre_Sales_Update__c.object-meta.xml
<CustomObject>
    <label>Pre Sales Update</label>
    <nameField>
        <label>Pre Sales Update Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre Sales Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Sales_Update__c/fields/Pre_Sales_Request__c.field-meta.xml
<CustomField>
    <fullName>Pre_Sales_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre Sales Request</label>
    <referenceTo>Pre_Sales_Request__c</referenceTo>
    <relationshipLabel>Pre Sales Updates</relationshipLabel>
    <relationshipName>Pre_Sales_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Pre_Sales_Update__c/fields/Pre_Sales_Update__c.field-meta.xml
<CustomField>
    <fullName>Pre_Sales_Update__c</fullName>
    <label>Pre Sales Update</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PreSalesUpdateController_TestClass.cls
@isTest(seeAllData= true)
public class PreSalesUpdateController_TestClass{
    public static testmethod void PreSalesUpdateController_Positivetest()
    {
        //Create new Pre-Sales Update
        Pre_Sales_Update__c testPSU = new Pre_Sales_Update__c();
        
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Pre_Sales_Request__c' LIMIT 1];
        
        Opportunity opp = new Opportunity();
        opp.Name = 'JM-Abc';
        opp.StageName = 'Proposal';
        Date tomorrow = date.today();
        tomorrow.addDays(1);
        opp.CloseDate = tomorrow;
        opp.Go_Live_Date__c = date.today();
        opp.Go_Live_Date_Approved__c = TRUE;
        insert opp;
        
        //Create new Pre-Sales Request
        Pre_Sales_Request__c testPSR = new Pre_Sales_Request__c();
        testPSR.RecordTypeId = rt.Id;
        testPSR.Opportunity__c = opp.Id;
        testPSR.Name = rt.Name + ' - ' + opp.Name;
        insert testPSR;
        
        Test.StartTest();
        PageReference pagetest = new PageReference('/apex/PreSalesUpdateCreation');
        pagetest.getParameters().put('currentPageURL','https://example.com/apex/PreSalesUpdateCreation?retUrl=/'+testPSR.Id+'%3Fisdtp%3Dmn');
        Test.setCurrentPageReference(pagetest);
        
        //Create an instance of the controller 
        redirectPreSalesUpdateController testController = new redirectPreSalesUpdateController(
        new ApexPages.StandardController(testPSU));
        
        //Calling method
        testController.getPreSalesRequestLandingPage();
        testController.redirectPreSalesUpdate();
        
        Test.StopTest();
    }
}