force-app/main/default/objects/Opportunity/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Go_Live_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Go Live Date Approved</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Opportunity/fields/Service_Delivery_Updates__c.field-meta.xml
<CustomField>
    <fullName>Service_Delivery_Updates__c</fullName>
    <label>ZDEPRECATED Service Delivery Updates</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Delivery_Updates__c/Service_Delivery_Updates__c.object-meta.xml
<CustomObject>
    <label>Service Delivery Update</label>
    <nameField>
        <label>Service Delivery Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Delivery Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Service_Delivery_Updates__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Delivery Updates</relationshipLabel>
    <relationshipName>Service_Delivery_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Service_Delivery_Updates__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Service Delivery Updates</relationshipLabel>
    <relationshipName>Service_Delivery_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <description>Used for internal requesting service request, i.e. Field Survey, Installation etc.</description>
    <label>Service Request</label>
    <nameField>
        <label>Service Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Service_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

DigicielFull/force-app/main/default/classes/secureSDUName_TestClass.cls
@isTest(seeAllData=true)
public class secureSDUName_TestClass{
    public static testmethod void secureSDUName_PositiveTest()
    {
        Test.StartTest();
        
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Service_Request__c' LIMIT 1];
        
        Opportunity opp = new Opportunity();
        opp.Name = 'JM-Abc';
        opp.StageName = 'Proposal';
        Date tomorrow = date.today();
        tomorrow.addDays(1);
        opp.CloseDate = tomorrow;
        opp.Go_Live_Date__c = date.today();
        opp.Go_Live_Date_Approved__c = TRUE;
        insert opp;
        
        
        //Create new Service Request
        Service_Request__c testSR = new Service_Request__c();
        testSR.RecordTypeId = rt.Id;
        testSR.Opportunity__c = opp.Id;
        // testSR.Name = rt.Name + ' - ' + opp.Name;
        insert testSR;
        
        // Create New Service Delivery Update
        Service_Delivery_Updates__c testSDU = new Service_Delivery_Updates__c();
        testSDU.Service_Request__c = testSR.Id;
        Datetime currentDate = Datetime.now();
        String currentDateStr = currentDate.format('dd-MM-yyyy');
        String objectFinalName = testSR.Name + ' - ' + currentDateStr;
        testSDU.Name = objectFinalName;
        
        // Test Insertion
        insert testSDU;
        Service_Delivery_Updates__c newObj = [Select Id,Name From Service_Delivery_Updates__c Where Id=:testSDU.Id];
        // System.assertEquals(objectFinalName,newObj.Name);
        
        newObj.Name = 'Changing The Name For Test';
        update newObj;
        
        Service_Delivery_Updates__c updatedObj = [Select Name From Service_Delivery_Updates__c Where Id=:testSDU.Id];
        // System.assertEquals(objectFinalName,updatedObj.Name);
        
        
        Test.StopTest();
    }
}