DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/Monthly_ICT_GSM_Targets__c.object-meta.xml
<CustomObject>
    <label>Monthly ICT &amp; GSM Targets</label>
    <nameField>
        <displayFormat>Digicel-{0000000}</displayFormat>
        <label>Monthly ICT &amp; GSM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly ICT &amp; GSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Is_Current_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Fiscal_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Fiscal Year</label>
    <type>Checkbox</type>
</CustomField>

DigicielFull/force-app/main/default/objects/Monthly_ICT_GSM_Targets__c/fields/Target_Month_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Month_Date__c</fullName>
    <label>Target Month Date</label>
    <type>Date</type>
</CustomField>

DigicielFull/force-app/main/default/classes/classVerifyMonthlyTargetsFiscalYear.cls
global class classVerifyMonthlyTargetsFiscalYear implements Schedulable{
	global void execute(SchedulableContext SC) {
		List<Monthly_ICT_GSM_Targets__c> listMonthlyTargets = [SELECT Id, Target_Month_Date__c,
												Is_Current_Fiscal_Year__c
												FROM Monthly_ICT_GSM_Targets__c
												WHERE (Target_Month_Date__c = THIS_FISCAL_YEAR
												AND Is_Current_Fiscal_Year__c = false)
												OR (Target_Month_Date__c != THIS_FISCAL_YEAR
												AND Is_Current_Fiscal_Year__c = true)];
		
		for(Monthly_ICT_GSM_Targets__c monthlyTarget: listMonthlyTargets){
			monthlyTarget.Is_Current_Fiscal_Year__c = !monthlyTarget.Is_Current_Fiscal_Year__c;
		}
		
		update listMonthlyTargets;
	}
}